/**
 * One source for the public legal texts. The site pages render these documents with
 * React (components/LegalDocumentBody.tsx), and scripts/generate-legal-mirrors.ts renders
 * the same documents to the static copies in the repo's legal/ folder, so the two can
 * never say different things. legal-mirrors.test.ts fails when a copy is out of date.
 *
 * Text uses two inline marks only: **bold** and [label](href). Site paths ("/terms")
 * stay relative on the site and become absolute in the static copies.
 */

export type LegalBlock =
  | { kind: 'paragraph'; text: string }
  | { kind: 'list'; items: string[] }
  | { kind: 'steps'; items: string[] }
  | { kind: 'subheading'; text: string };

export interface LegalSection {
  id: string;
  heading: string;
  blocks: LegalBlock[];
}

export interface LegalDocument {
  title: string;
  /** Shown under the title, e.g. "Last updated: September 24, 2026". */
  intro: string;
  /** Site path of the canonical page, e.g. "/privacy". */
  path: string;
  sections: LegalSection[];
}

export type InlineToken =
  | { kind: 'text'; text: string }
  | { kind: 'strong'; text: string }
  | { kind: 'link'; text: string; href: string };

const INLINE_PATTERN = /\*\*([^*]+)\*\*|\[([^\]]+)\]\(([^)\s]+)\)/g;

export function parseInline(text: string): InlineToken[] {
  const tokens: InlineToken[] = [];
  let cursor = 0;
  for (const match of text.matchAll(INLINE_PATTERN)) {
    const start = match.index ?? 0;
    if (start > cursor) tokens.push({ kind: 'text', text: text.slice(cursor, start) });
    if (match[1] !== undefined) {
      tokens.push({ kind: 'strong', text: match[1] });
    } else {
      tokens.push({ kind: 'link', text: match[2], href: match[3] });
    }
    cursor = start + match[0].length;
  }
  if (cursor < text.length) tokens.push({ kind: 'text', text: text.slice(cursor) });
  return tokens;
}

/** Plain text of a marked-up string, for metadata and tests. */
export function plainText(text: string): string {
  return parseInline(text)
    .map((token) => token.text)
    .join('');
}

export function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function absoluteHref(href: string, siteUrl: string): string {
  return href.startsWith('/') ? `${siteUrl}${href}` : href;
}

function renderInlineHtml(text: string, siteUrl: string): string {
  return parseInline(text)
    .map((token) => {
      if (token.kind === 'strong') return `<strong>${escapeHtml(token.text)}</strong>`;
      if (token.kind === 'link') {
        return `<a href="${escapeHtml(absoluteHref(token.href, siteUrl))}">${escapeHtml(token.text)}</a>`;
      }
      return escapeHtml(token.text);
    })
    .join('');
}

function renderBlockHtml(block: LegalBlock, siteUrl: string): string {
  switch (block.kind) {
    case 'paragraph':
      return `    <p>${renderInlineHtml(block.text, siteUrl)}</p>`;
    case 'subheading':
      return `    <h3>${renderInlineHtml(block.text, siteUrl)}</h3>`;
    case 'list':
    case 'steps': {
      const tag = block.kind === 'list' ? 'ul' : 'ol';
      const items = block.items
        .map((item) => `      <li>${renderInlineHtml(item, siteUrl)}</li>`)
        .join('\n');
      return `    <${tag}>\n${items}\n    </${tag}>`;
    }
  }
}

const MIRROR_STYLE = `        * { box-sizing: border-box; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
            line-height: 1.6;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            color: #333;
            background: #fafafa;
        }
        h1 { color: #1a1a2e; border-bottom: 2px solid #4a7c59; padding-bottom: 10px; }
        h2 { color: #4a7c59; margin-top: 30px; }
        .updated { color: #666; font-size: 14px; }
        .mirror { background: #eef4ef; border-left: 4px solid #4a7c59; padding: 12px 16px; margin: 20px 0 30px; }
        a { color: #4a7c59; }`;

/**
 * Static HTML copy of a document for the legal/ folder (served separately from the site).
 * It names the site page as the version that applies.
 */
export function renderLegalMirrorHtml(document: LegalDocument, siteUrl: string): string {
  const canonicalUrl = `${siteUrl}${document.path}`;
  const sections = document.sections
    .map((section) =>
      [
        `    <h2 id="${escapeHtml(section.id)}">${renderInlineHtml(section.heading, siteUrl)}</h2>`,
        ...section.blocks.map((block) => renderBlockHtml(block, siteUrl)),
      ].join('\n')
    )
    .join('\n\n');

  return `<!DOCTYPE html>
<!-- Generated by apps/site/scripts/generate-legal-mirrors.ts from apps/site/lib/legal.
     Do not edit by hand: change the source and run \`npm run legal:mirrors -w @everybible/site\`. -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${escapeHtml(document.title)} - EveryBible</title>
    <link rel="canonical" href="${escapeHtml(canonicalUrl)}">
    <style>
${MIRROR_STYLE}
    </style>
</head>
<body>
    <h1>${escapeHtml(document.title)}</h1>
    <p class="updated">${escapeHtml(document.intro)}</p>
    <p class="mirror">This is a copy of <a href="${escapeHtml(canonicalUrl)}">${escapeHtml(canonicalUrl)}</a>. If the two ever differ, the version on everybible.app applies.</p>

${sections}
</body>
</html>
`;
}
