import assert from 'node:assert/strict';
import test from 'node:test';

import {
  parseInline,
  plainText,
  renderLegalMirrorHtml,
  type LegalDocument,
} from './legal-document';

test('parseInline splits bold and links out of plain text', () => {
  assert.deepEqual(parseInline('Go to **More** or read [the policy](/privacy).'), [
    { kind: 'text', text: 'Go to ' },
    { kind: 'strong', text: 'More' },
    { kind: 'text', text: ' or read ' },
    { kind: 'link', text: 'the policy', href: '/privacy' },
    { kind: 'text', text: '.' },
  ]);
  assert.deepEqual(parseInline('no marks'), [{ kind: 'text', text: 'no marks' }]);
  assert.equal(plainText('Email [us](mailto:a@b.c) **now**'), 'Email us now');
});

const sample: LegalDocument = {
  title: 'Sample <Policy>',
  intro: 'Last updated: today',
  path: '/sample',
  sections: [
    {
      id: 'one',
      heading: 'One',
      blocks: [
        { kind: 'paragraph', text: 'See [terms](/terms) & [mail](mailto:hello@everybible.app).' },
        { kind: 'steps', items: ['Tap **More**'] },
      ],
    },
  ],
};

test('the static copy escapes text, names the canonical page and makes site links absolute', () => {
  const html = renderLegalMirrorHtml(sample, 'https://everybible.app');

  assert.match(html, /<title>Sample &lt;Policy&gt; - EveryBible<\/title>/);
  assert.match(html, /<link rel="canonical" href="https:\/\/everybible.app\/sample">/);
  assert.match(html, /This is a copy of <a href="https:\/\/everybible.app\/sample">/);
  assert.match(html, /<a href="https:\/\/everybible.app\/terms">terms<\/a> &amp; /);
  assert.match(html, /<a href="mailto:hello@everybible.app">mail<\/a>/);
  assert.match(html, /<ol>\n {6}<li>Tap <strong>More<\/strong><\/li>\n {4}<\/ol>/);
  assert.match(html, /Generated by apps\/site\/scripts\/generate-legal-mirrors.ts/);
});
