import { StyleSheet } from 'react-native';
import { layout, radius, shadows, spacing, typography } from '../../../design/system';
import { FOLLOW_ALONG_VERSE_LINE_HEIGHT } from '../bibleReaderModel';
import { AUDIO_PORTION_HANDLE_WIDTH, FEEDBACK_AUDIO_COUNTDOWN_SIZE } from './readerConstants';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  premiumReaderLayout: {
    flex: 1,
  },
  planSessionBottomBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 40,
    borderTopWidth: 1,
  },
  planSessionBottomBarContent: {
    flex: 1,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
    paddingBottom: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
  },
  planSessionBottomBarArrowButton: {
    width: layout.minTouchTarget,
    height: layout.minTouchTarget,
    alignItems: 'center',
    justifyContent: 'center',
  },
  planSessionBottomBarCompleteButton: {
    borderRadius: layout.minTouchTarget / 2,
  },
  planSessionBottomBarArrowSpacer: {
    width: layout.minTouchTarget,
    height: layout.minTouchTarget,
  },
  planSessionBottomBarCopy: {
    flex: 1,
    gap: 2,
    justifyContent: 'center',
  },
  planSessionBottomBarCopyCentered: {
    alignItems: 'center',
  },
  planSessionBottomBarCopyListenMode: {
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
  },
  planSessionBottomBarTitle: {
    ...typography.bodyStrong,
    fontSize: 15,
    lineHeight: 19,
    letterSpacing: -0.2,
    textAlign: 'center',
  },
  planSessionBottomBarMeta: {
    ...typography.micro,
    fontVariant: ['tabular-nums'],
    fontWeight: '700',
    textAlign: 'center',
  },
  glassSurface: {
    overflow: 'hidden',
    borderRadius: radius.pill,
    backgroundColor: 'transparent',
  },
  glassStroke: {
    ...StyleSheet.absoluteFillObject,
    borderWidth: 1,
    borderRadius: radius.pill,
  },
  glassContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  floatingReaderTopBar: {
    position: 'absolute',
    left: 24,
    right: 22,
    zIndex: 30,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  floatingReaderReferenceCluster: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    flexShrink: 1,
  },
  floatingReaderTopActionGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: spacing.xs,
    flexShrink: 0,
  },
  floatingReaderPlanExitButton: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dynamicIslandTopMask: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 29,
  },
  floatingReaderReferencePill: {
    minWidth: 124,
    maxWidth: 212,
    height: layout.minTouchTarget,
    flexDirection: 'row',
    alignItems: 'stretch',
    alignSelf: 'center',
    flexShrink: 1,
  },
  floatingReaderReferencePillBackground: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 2,
    height: layout.iconButton,
    borderRadius: radius.lg,
    borderWidth: StyleSheet.hairlineWidth,
    overflow: 'hidden',
  },
  floatingReaderReferencePillSegment: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    minWidth: layout.minTouchTarget,
    flexShrink: 1,
  },
  floatingReaderReferencePillBookSegment: {
    paddingHorizontal: 16,
  },
  floatingReaderReferencePillPrimary: {
    ...typography.label,
    fontSize: 14,
    lineHeight: 17,
    fontWeight: '700',
    letterSpacing: 0,
    flexShrink: 1,
  },
  floatingReaderReferencePillDivider: {
    width: 1,
    height: 32,
    alignSelf: 'center',
    opacity: 0.55,
  },
  floatingReaderReferencePillTranslation: {
    ...typography.label,
    fontSize: 14,
    lineHeight: 17,
    fontWeight: '700',
    letterSpacing: 0,
    flexShrink: 1,
  },
  floatingReaderMenuButton: {
    width: layout.iconButton,
    height: layout.iconButton,
    borderRadius: radius.lg,
    borderWidth: StyleSheet.hairlineWidth,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  floatingReaderMenuButtonContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  floatingReaderChapterNavOverlay: {
    position: 'absolute',
    left: spacing.lg,
    right: spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    zIndex: 26,
  },
  floatingReaderChapterNavButton: {
    width: layout.minTouchTarget,
    height: layout.minTouchTarget,
    borderWidth: 1,
    borderRadius: radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  premiumReaderScrollContent: {
    flexGrow: 1,
    paddingHorizontal: spacing.xl,
  },
  premiumReaderContentShell: {
    maxWidth: 560,
    width: '100%',
    alignSelf: 'center',
  },
  premiumReaderVirtualFooter: {
    height: 1,
  },
  disabledSessionModeButton: {
    opacity: 0.45,
  },
  scrollView: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 12,
    paddingTop: spacing.lg,
  },
  immersiveContent: {
    flexGrow: 1,
  },
  readerShell: {
    maxWidth: 560,
    width: '100%',
    alignSelf: 'center',
  },
  immersiveReaderShell: {
    flex: 1,
  },
  audioFirstShell: {
    flex: 1,
  },
  readerColumn: {
    gap: 20,
  },
  premiumReaderColumn: {
    gap: 20,
  },
  readerParagraph: {
    gap: 0,
  },
  listenColumn: {
    flex: 1,
    gap: 20,
    justifyContent: 'flex-start',
  },
  listenArtworkFrame: {
    alignSelf: 'stretch',
    width: '100%',
    aspectRatio: 1,
    borderRadius: radius.lg,
    borderWidth: 1,
    overflow: 'hidden',
  },
  listenArtwork: {
    width: '100%',
    height: '100%',
  },
  listenPlayerCard: {
    paddingBottom: 0,
    gap: 12,
  },
  listenCountedNoticeCard: {
    borderWidth: 1,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    gap: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
  },
  listenCountedNoticeText: {
    flex: 1,
    ...typography.micro,
    fontWeight: '700',
  },
  listenProgressTouch: {
    justifyContent: 'center',
    height: 22,
  },
  listenProgressTrack: {
    height: 5,
    borderRadius: radius.pill,
    overflow: 'hidden',
  },
  listenProgressFill: {
    height: '100%',
    borderRadius: radius.pill,
  },
  listenTimeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
    gap: 12,
  },
  listenTimeText: {
    fontSize: 12,
    fontWeight: '600',
    minWidth: 42,
    fontVariant: ['tabular-nums'],
  },
  listenFeedbackCard: {
    borderWidth: 1,
    borderRadius: radius.lg,
    padding: 16,
    gap: 14,
  },
  listenFeedbackHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  listenFeedbackHeaderStacked: {
    flexDirection: 'column',
  },
  listenFeedbackCopy: {
    flex: 1,
    gap: 4,
  },
  listenFeedbackCopyStacked: {
    // flex: 1 in a column would try to fill a height the card does not have.
    flex: 0,
  },
  listenFeedbackTitle: {
    fontSize: 17,
    fontWeight: '700',
  },
  listenFeedbackBody: {
    fontSize: 13,
    lineHeight: 19,
  },
  listenFeedbackIdentityPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: radius.lg,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  listenFeedbackIdentityText: {
    flexShrink: 1,
    fontSize: 11,
    fontWeight: '700',
  },
  listenFeedbackIdentityTextCompact: {
    maxWidth: 110,
  },
  listenSentimentButton: {
    flex: 1,
    minHeight: layout.minTouchTarget,
    borderWidth: 1,
    borderRadius: radius.lg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  listenFeedbackInput: {
    minHeight: 96,
    borderWidth: 1,
    borderRadius: radius.lg,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    fontSize: 15,
    lineHeight: 21,
    textAlignVertical: 'top',
  },
  listenFeedbackHint: {
    fontSize: 12,
    lineHeight: 17,
  },
  listenFeedbackSubmitButton: {
    minWidth: 0,
  },
  readerBlock: {
    gap: 10,
    paddingHorizontal: 12,
  },
  premiumReaderBlock: {
    gap: 6,
    paddingHorizontal: 0,
  },
  readerVerse: {
    alignSelf: 'stretch',
  },
  structuredVerse: {
    borderRadius: radius.sm,
    paddingVertical: 2,
  },
  premiumStructuredVerse: {
    paddingVertical: 4,
  },
  structuredVerseLine: {
    alignSelf: 'stretch',
  },
  structuredVerseContinuation: {
    marginTop: 2,
  },
  sectionHeading: {
    ...typography.readingHeading,
    // Carried for the platform-serif fallback used by non-Latin scripts, where no named
    // bold family is available and fontWeight is what actually thickens the glyphs.
    fontWeight: '700',
    marginTop: 8,
    marginBottom: 4,
  },
  premiumSectionHeading: {
    ...typography.readingHeading,
    textTransform: 'none',
    marginTop: 18,
    marginBottom: 8,
  },
  verseText: {
    fontWeight: '400',
    letterSpacing: 0.2,
  },
  premiumVerseText: {
    ...typography.readingBody,
    letterSpacing: 0,
  },
  inlineVerseNumber: {
    fontWeight: '600',
  },
  premiumVerseNumber: {
    ...typography.readingVerseNumber,
  },
  premiumParagraphText: {
    includeFontPadding: false,
  },
  premiumInlineVerse: {},
  premiumInlineVerseNumber: {},
  feedbackCard: {
    borderWidth: 1,
    borderRadius: radius.lg,
    padding: 24,
    gap: 14,
    minHeight: 220,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  feedbackTitle: {
    fontSize: 18,
    fontWeight: '700',
  },
  feedbackBody: {
    fontSize: 15,
    lineHeight: 24,
  },
  feedbackButton: {
    borderRadius: radius.lg,
    paddingHorizontal: 18,
    paddingVertical: 12,
    minHeight: layout.minTouchTarget,
    alignItems: 'center',
    justifyContent: 'center',
  },
  feedbackButtonText: {
    fontSize: 14,
    fontWeight: '700',
  },
  fontSheetOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  fontSheetBackdrop: {
    flex: 1,
  },
  modalBackdropFill: {
    flex: 1,
    justifyContent: 'flex-start',
    paddingHorizontal: 16,
  },
  actionSheet: {
    borderRadius: radius.lg,
    borderWidth: 1,
    padding: 18,
    gap: 8,
  },
  actionSheetTitle: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 4,
  },
  actionRow: {
    borderWidth: 1,
    borderRadius: radius.lg,
    paddingHorizontal: 14,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  actionLabel: {
    fontSize: 15,
    fontWeight: '700',
  },
  feedbackModalOverlay: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
  },
  chapterAudioShareLoadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    zIndex: 50,
  },
  chapterAudioShareLoadingCard: {
    minWidth: 220,
    borderRadius: radius.lg,
    borderWidth: 1,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.lg,
    alignItems: 'center',
    gap: spacing.sm,
  },
  chapterAudioShareLoadingTitle: {
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },
  chapterAudioShareLoadingBody: {
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
  audioShareBackdrop: {
    flex: 1,
    justifyContent: 'flex-end',
    paddingHorizontal: spacing.md,
    paddingTop: spacing.xxl,
  },
  audioShareSheet: {
    borderRadius: 20,
    borderWidth: 1,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.lg,
    gap: spacing.md,
    ...shadows.floating,
  },
  audioOptionsSheet: {
    borderRadius: 20,
    borderWidth: 1,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.lg,
    gap: spacing.md,
    ...shadows.floating,
  },
  audioOptionsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  audioOptionsTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    flex: 1,
  },
  audioOptionsTitle: {
    ...typography.cardTitle,
    fontSize: 18,
    lineHeight: 22,
  },
  sheetCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  audioShareGrabber: {
    width: 44,
    height: 4,
    borderRadius: radius.pill,
    alignSelf: 'center',
    opacity: 0.9,
  },
  audioShareHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  audioShareTitleWrap: {
    flex: 1,
    gap: 2,
  },
  audioShareEyebrow: {
    ...typography.eyebrow,
    fontSize: 10,
    lineHeight: 12,
    letterSpacing: 1.1,
  },
  audioShareTitle: {
    ...typography.cardTitle,
    fontSize: 21,
    lineHeight: 26,
    letterSpacing: -0.35,
  },
  audioShareCloseButton: {
    width: 34,
    height: 34,
    borderRadius: radius.pill,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  audioShareOption: {
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: spacing.md,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  audioShareOptionIconWrap: {
    width: 32,
    height: 32,
    borderRadius: radius.pill,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  audioShareOptionLabel: {
    ...typography.bodyStrong,
    flex: 1,
    fontSize: 15,
    lineHeight: 20,
  },
  audioPortionSheet: {
    borderRadius: radius.lg,
    borderWidth: 1,
    padding: spacing.lg,
    gap: spacing.sm,
    ...shadows.floating,
  },
  audioPortionTitle: {
    ...typography.cardTitle,
    fontSize: 20,
    lineHeight: 24,
  },
  audioPortionReference: {
    ...typography.label,
    fontSize: 12,
    lineHeight: 17,
    letterSpacing: 0.3,
  },
  audioPortionRangeHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: spacing.xs,
    gap: spacing.md,
  },
  audioPortionRangeLabelWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  audioPortionRangeTime: {
    ...typography.bodyStrong,
    fontSize: 14,
    lineHeight: 18,
    fontVariant: ['tabular-nums'],
  },
  audioPortionRangeSelector: {
    height: 72,
    borderRadius: 16,
    justifyContent: 'center',
    marginTop: spacing.xs,
    marginBottom: spacing.xs,
    overflow: 'hidden',
  },
  audioPortionRangeTrack: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 16,
    opacity: 0.45,
  },
  audioPortionRangeSelection: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    borderRadius: 16,
    opacity: 0.6,
  },
  audioPortionWaveRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    height: 54,
  },
  audioPortionWaveBar: {
    width: 3,
    borderRadius: radius.pill,
    opacity: 0.95,
  },
  audioPortionPreviewNeedle: {
    position: 'absolute',
    top: 6,
    bottom: 6,
    width: 2,
    borderRadius: radius.pill,
    marginLeft: -1,
  },
  audioPortionHandle: {
    position: 'absolute',
    top: 8,
    bottom: 8,
    width: AUDIO_PORTION_HANDLE_WIDTH,
    borderRadius: radius.pill,
    justifyContent: 'center',
    alignItems: 'center',
  },
  audioPortionHandleStart: {
    marginLeft: 0,
  },
  audioPortionHandleEnd: {
    marginLeft: 0,
  },
  audioPortionHandleGrip: {
    width: 2,
    height: 22,
    borderRadius: radius.pill,
    opacity: 0.88,
  },
  audioPortionPreviewButton: {
    alignSelf: 'center',
    minHeight: 36,
    borderRadius: radius.lg,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 2,
    marginBottom: 4,
  },
  audioPortionPreviewLabel: {
    ...typography.label,
    fontVariant: ['tabular-nums'],
  },
  audioPortionActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  audioPortionActionButton: {
    flex: 1,
    minHeight: layout.minTouchTarget,
    borderRadius: radius.lg,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
  },
  audioPortionShareButton: {
    flex: 1.2,
  },
  audioPortionActionLabel: {
    ...typography.button,
    fontSize: 15,
    lineHeight: 20,
  },
  feedbackModalBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  feedbackModalCard: {
    borderRadius: radius.lg,
    borderWidth: 1,
    maxHeight: '85%',
    overflow: 'hidden',
  },
  feedbackModalScroll: {
    maxHeight: '100%',
  },
  feedbackModalScrollContent: {
    gap: spacing.md,
    padding: spacing.lg,
  },
  feedbackModalTitle: {
    fontSize: 18,
    fontWeight: '700',
  },
  feedbackModalReference: {
    ...typography.label,
    fontSize: 12,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  feedbackModalBody: {
    fontSize: 14,
    lineHeight: 21,
  },
  feedbackSentimentRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  feedbackSentimentButton: {
    flex: 1,
    borderWidth: 1,
    borderRadius: radius.lg,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.md,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
  },
  feedbackSentimentLabel: {
    fontSize: 14,
    fontWeight: '700',
  },
  feedbackCommentInput: {
    minHeight: 120,
    borderWidth: 1,
    borderRadius: radius.lg,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    fontSize: 15,
    lineHeight: 21,
    textAlignVertical: 'top',
  },
  feedbackCharCount: {
    ...typography.micro,
    alignSelf: 'flex-end',
    marginTop: spacing.xs,
  },
  feedbackAudioCard: {
    borderWidth: 1,
    borderRadius: radius.lg,
    padding: spacing.md,
    gap: spacing.sm,
  },
  feedbackAudioCardCompact: {
    padding: spacing.sm,
  },
  feedbackAudioHeader: {
    gap: 4,
  },
  feedbackAudioHeaderMain: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  feedbackAudioCountdown: {
    width: FEEDBACK_AUDIO_COUNTDOWN_SIZE,
    height: FEEDBACK_AUDIO_COUNTDOWN_SIZE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  feedbackAudioCountdownSvg: {
    position: 'absolute',
  },
  feedbackAudioCountdownText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    fontVariant: ['tabular-nums'],
  },
  feedbackAudioStatus: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  feedbackAudioStatusText: {
    flex: 1,
    fontSize: 14,
    fontWeight: '700',
  },
  feedbackAudioLimitText: {
    fontSize: 12,
    lineHeight: 16,
  },
  feedbackAudioHelpText: {
    fontSize: 12,
    lineHeight: 16,
  },
  feedbackAudioHelpRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  feedbackAudioHelpMessage: {
    flex: 1,
  },
  feedbackAudioHelpLink: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '600',
  },
  feedbackAudioActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  feedbackAudioButton: {
    minHeight: layout.minTouchTarget,
    borderWidth: 1,
    borderRadius: radius.lg,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
    gap: spacing.xs,
  },
  feedbackAudioButtonText: {
    fontSize: 13,
    fontWeight: '700',
  },
  feedbackAudioIconButton: {
    width: layout.minTouchTarget,
    height: layout.minTouchTarget,
    borderWidth: 1,
    borderRadius: radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  feedbackAudioUploading: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  feedbackErrorText: {
    fontSize: 13,
    lineHeight: 18,
  },
  translatorReviewCard: {
    borderWidth: 1,
    borderRadius: radius.lg,
    padding: 16,
    marginBottom: 20,
    gap: 12,
  },
  translatorReviewHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  translatorReviewHeaderCopy: {
    flex: 1,
    gap: 4,
  },
  translatorReviewTitle: {
    fontSize: 18,
    fontWeight: '700',
  },
  translatorReviewMeta: {
    fontSize: 13,
    lineHeight: 18,
  },
  translatorReviewRefreshButton: {
    width: 36,
    height: 36,
    borderRadius: radius.sm,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  translatorReviewLoadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  translatorReviewItem: {
    borderWidth: 1,
    borderRadius: radius.md,
    padding: 12,
    gap: 8,
  },
  translatorReviewItemHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  translatorReviewSentimentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexShrink: 1,
  },
  translatorReviewItemTitle: {
    fontSize: 15,
    fontWeight: '700',
  },
  translatorReviewBadge: {
    borderRadius: radius.lg,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  translatorReviewBadgeText: {
    fontSize: 11,
    fontWeight: '700',
  },
  translatorReviewComment: {
    fontSize: 15,
    lineHeight: 22,
  },
  translatorReviewActionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  translatorReviewActionButton: {
    minHeight: 40,
    borderWidth: 1,
    borderRadius: radius.sm,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  translatorReviewActionLabel: {
    fontSize: 13,
    fontWeight: '700',
  },
  verseImageSheetOverlay: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
  },
  verseImageSheetBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  verseImageSheetCard: {
    borderRadius: radius.lg,
    borderWidth: 1,
    overflow: 'hidden',
    maxHeight: '88%',
  },
  verseImageSheetHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.md,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: spacing.md,
  },
  verseImageSheetHeaderCopy: {
    flex: 1,
    gap: 2,
  },
  verseImageSheetTitle: {
    fontSize: 17,
    fontWeight: '700',
  },
  verseImageSheetReference: {
    ...typography.label,
    fontSize: 12,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  verseImageSheetCloseButton: {
    width: layout.minTouchTarget,
    height: layout.minTouchTarget,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.pill,
    borderWidth: 1,
  },
  verseImagePreviewFrame: {
    marginHorizontal: spacing.lg,
    borderRadius: radius.lg,
    overflow: 'hidden',
    aspectRatio: 1.08,
  },
  verseImagePreviewBackground: {
    flex: 1,
    justifyContent: 'space-between',
  },
  verseImagePreviewImage: {
    borderRadius: radius.lg,
  },
  verseImagePreviewOverlay: {
    ...StyleSheet.absoluteFillObject,
  },
  verseImagePreviewContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.xl,
    gap: spacing.lg,
  },
  verseImagePreviewText: {
    ...typography.readingDisplay,
    textAlign: 'center',
    letterSpacing: -0.2,
  },
  verseImagePreviewReference: {
    ...typography.label,
    textAlign: 'center',
    fontWeight: '700',
  },
  verseImageBackgroundRail: {
    gap: spacing.sm,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: spacing.md,
  },
  verseImageBackgroundButton: {
    borderRadius: radius.lg,
    borderWidth: 1,
    overflow: 'hidden',
  },
  verseImageBackgroundTile: {
    width: 88,
    height: 118,
    justifyContent: 'flex-end',
  },
  verseImageBackgroundTileImage: {
    borderRadius: radius.lg,
  },
  verseImageBackgroundSelectedBadge: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 22,
    height: 22,
    borderRadius: radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  verseImageSheetActions: {
    flexDirection: 'row',
    gap: spacing.sm,
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.lg,
    paddingTop: spacing.xs,
  },
  verseImageSheetActionButton: {
    flex: 1,
    minHeight: layout.minTouchTarget,
    borderRadius: radius.lg,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  verseImageSheetShareButton: {
    minWidth: 132,
  },
  verseImageSheetActionText: {
    fontSize: 14,
    fontWeight: '700',
  },
  feedbackActionRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  feedbackActionButton: {
    flex: 1,
    minHeight: layout.minTouchTarget,
    borderWidth: 1,
    borderRadius: radius.lg,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  feedbackSubmitButton: {
    minWidth: 132,
  },
  feedbackActionLabel: {
    fontSize: 14,
    fontWeight: '700',
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalBackdrop: {
    flex: 1,
  },
  modalContent: {
    borderTopLeftRadius: radius.lg,
    borderTopRightRadius: radius.lg,
    borderWidth: 1,
    paddingTop: 20,
    height: '78%',
    overflow: 'hidden',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginBottom: 12,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '700',
  },
  audioOptionsList: {
    paddingHorizontal: 20,
    paddingBottom: 20,
    gap: 12,
  },
  audioOptionCard: {
    borderWidth: 1,
    borderRadius: radius.lg,
    padding: 16,
    gap: 8,
  },
  audioOptionLabel: {
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  audioOptionValue: {
    fontSize: 14,
    lineHeight: 20,
  },
  translationList: {
    paddingHorizontal: 20,
    paddingBottom: 12,
  },
  translationCard: {
    marginBottom: 12,
    borderRadius: radius.lg,
    borderWidth: 1,
  },
  translationItem: {
    minHeight: 88,
    paddingVertical: 16,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  translationInfo: {
    flex: 1,
  },
  translationNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 4,
  },
  translationName: {
    fontSize: 16,
    fontWeight: '700',
  },
  translationAbbr: {
    fontSize: 12,
    fontWeight: '700',
  },
  translationDescription: {
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 8,
  },
  translationMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  translationSize: {
    fontSize: 12,
    fontWeight: '500',
  },
  downloadedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  downloadedText: {
    fontSize: 12,
    fontWeight: '600',
  },
  followAlongContainer: {
    flex: 1,
  },
  followAlongHeader: {
    paddingHorizontal: 18,
    paddingBottom: 16,
    borderBottomWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  followAlongTitleCenter: {
    position: 'absolute',
    left: 0,
    right: 0,
    alignItems: 'center',
  },
  followAlongEyebrow: {
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  followAlongTitle: {
    fontSize: 18,
    fontWeight: '700',
  },
  followAlongCloseButton: {
    borderWidth: 1,
    borderRadius: radius.pill,
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    zIndex: 1,
  },
  followAlongCloseLabel: {
    fontSize: 13,
    fontWeight: '700',
  },
  followAlongScrollView: {
    flex: 1,
  },
  followAlongContent: {
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 28,
    gap: 12,
  },
  followAlongVerseRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  followAlongVerseIndicator: {
    width: 3,
    alignSelf: 'stretch',
    borderRadius: radius.pill,
    minHeight: FOLLOW_ALONG_VERSE_LINE_HEIGHT,
  },
  followAlongVerseContent: {
    flex: 1,
    gap: 8,
  },
  followAlongHeading: {
    ...typography.readingHeading,
  },
  followAlongVerseText: {
    ...typography.readingBody,
    fontSize: 18,
    lineHeight: FOLLOW_ALONG_VERSE_LINE_HEIGHT,
  },
  followAlongVerseNumber: {
    ...typography.readingVerseNumber,
    fontSize: 12,
  },
  fontSheet: {
    borderTopWidth: 1,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: 16,
    gap: 16,
  },
  fontSheetHandle: {
    width: 44,
    height: 4,
    borderRadius: radius.pill,
    alignSelf: 'center',
  },
  fontSheetTitle: {
    fontSize: 18,
    fontWeight: '700',
    textAlign: 'center',
  },
  readerFontStepperRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  readerFontStepperButton: {
    flex: 1,
    minHeight: 64,
    borderRadius: radius.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  readerFontStepperButtonLarge: {
    flex: 1.2,
  },
  readerFontStepperDisabled: {
    opacity: 0.48,
  },
  readerFontStepperText: {
    fontWeight: '500',
  },
  readerFontStepperSmallText: {
    fontSize: 26,
    lineHeight: 32,
  },
  readerFontStepperLargeText: {
    fontSize: 42,
    lineHeight: 48,
  },
  readerFontPreview: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.md,
    paddingVertical: spacing.md,
  },
  readerFontPreviewSpecimen: {
    textAlign: 'center',
  },
  readerThemeModeRail: {
    gap: 10,
    paddingRight: 2,
  },
  readerThemeTileColumn: {
    width: 128,
    alignItems: 'center',
    gap: spacing.sm,
  },
  readerThemeTileLabel: {
    ...typography.micro,
    textAlign: 'center',
  },
  readerThemeTile: {
    width: 128,
    height: 112,
    borderRadius: radius.lg,
    borderWidth: 1,
    padding: 10,
    justifyContent: 'space-between',
    overflow: 'hidden',
  },
  readerThemePaper: {
    minHeight: 60,
    borderRadius: radius.md,
    borderWidth: 1,
    padding: 10,
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 3,
  },
  readerThemeLineStack: {
    gap: 8,
  },
  readerThemeLine: {
    width: '82%',
    height: 4,
    borderRadius: radius.pill,
    opacity: 0.88,
  },
  readerThemeLineMedium: {
    width: '64%',
  },
  readerThemeLineShort: {
    width: '48%',
  },
  readerThemeCheckCircle: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  readerPaletteRail: {
    gap: 10,
    paddingRight: 2,
  },
  readerPaletteTile: {
    width: 116,
    height: 96,
    borderRadius: radius.lg,
    borderWidth: 1,
    padding: 12,
    justifyContent: 'space-between',
    overflow: 'hidden',
  },
  readerPaletteSwatches: {
    flexDirection: 'row',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    width: 76,
    height: 34,
  },
  readerPaletteGradient: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: radius.pill,
    opacity: 0.38,
  },
  readerPaletteSwatch: {
    width: 24,
    height: 34,
    borderRadius: radius.pill,
    borderWidth: 2,
    marginHorizontal: -4,
  },
  readerAllSettingsButton: {
    minHeight: layout.minTouchTarget,
    alignItems: 'center',
    justifyContent: 'center',
  },
  readerAllSettingsLabel: {
    fontSize: 16,
    fontWeight: '700',
  },
  fontOptionRow: {
    flexDirection: 'row',
    gap: 10,
  },
  fontOptionButton: {
    flex: 1,
    borderWidth: 1,
    borderRadius: radius.lg,
    paddingVertical: 14,
    alignItems: 'center',
    gap: 8,
  },
  fontOptionSample: {
    fontWeight: '700',
  },
  fontOptionLabel: {
    fontSize: 12,
    fontWeight: '700',
  },
});
