#!/usr/bin/env python3
"""Write which characters each verse-picture face can draw.

The picture editor offers only the faces that have a glyph for every character in
the verse being shared, whatever its language: a Russian verse gets the faces with
Cyrillic, a Hindi one none of them (it keeps the platform font). This reads each
bundled font's character map and writes it as compact code point ranges.

Run after adding or changing a face:
  python3 -m pip install fonttools
  python3 scripts/generate-verse-image-font-coverage.py
  npx prettier --write src/screens/bible/reader/verseImage/verseImageFontCoverage.generated.ts
"""

from pathlib import Path

from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
FONTS = {
    'classic': 'node_modules/@expo-google-fonts/lora/400Regular_Italic/Lora_400Regular_Italic.ttf',
    'script': 'node_modules/@expo-google-fonts/dancing-script/600SemiBold/DancingScript_600SemiBold.ttf',
    'handwritten': 'node_modules/@expo-google-fonts/caveat/600SemiBold/Caveat_600SemiBold.ttf',
    'block': 'node_modules/@expo-google-fonts/anton/400Regular/Anton_400Regular.ttf',
    'slab': 'node_modules/@expo-google-fonts/alfa-slab-one/400Regular/AlfaSlabOne_400Regular.ttf',
    'elegant': 'node_modules/@expo-google-fonts/playfair-display/600SemiBold_Italic/PlayfairDisplay_600SemiBold_Italic.ttf',
    'typewriter': 'node_modules/@expo-google-fonts/special-elite/400Regular/SpecialElite_400Regular.ttf',
    'modern': 'assets/fonts/AlteHaasGrotesk-Bold.ttf',
}
OUT = ROOT / 'src/screens/bible/reader/verseImage/verseImageFontCoverage.generated.ts'


def ranges(code_points):
    result = []
    for cp in sorted(code_points):
        if result and cp == result[-1][1] + 1:
            result[-1][1] = cp
        else:
            result.append([cp, cp])
    return result


def main():
    lines = [
        '// Generated by scripts/generate-verse-image-font-coverage.py. Do not edit.',
        "import type { VerseImageFontId } from './verseImageStyle';",
        '',
        '/** Each face\'s drawable code points, as sorted inclusive [first, last] ranges. */',
        'export const VERSE_IMAGE_FONT_COVERAGE: Record<VerseImageFontId, readonly (readonly [number, number])[]> = {',
    ]
    for font_id, rel in FONTS.items():
        cmap = TTFont(ROOT / rel).getBestCmap()
        spans = ranges(cmap.keys())
        body = ', '.join(f'[{a}, {b}]' for a, b in spans)
        lines.append(f'  {font_id}: [{body}],')
        print(f'{font_id}: {len(cmap)} characters in {len(spans)} ranges')
    lines.append('};')
    OUT.write_text('\n'.join(lines) + '\n')
    print(f'wrote {OUT.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
