-- Placeholder for a live-only history row (production version 20260710094049).
--
-- This was an earlier draft of get_admin_analytics_overview applied via MCP and
-- immediately superseded by 20260710094508_fix_listening_minutes_double_count.sql.
-- Its statements remain in supabase_migrations.schema_migrations. Intentionally a
-- no-op so local history matches production without replaying the draft.
