-- Generated by scripts/export_translation_text_packs.py
-- Updates current translation catalogs so all text packs resolve from R2.

begin;

update translation_catalog
set catalog = '{"version":"2026.03.24-v1","updatedAt":"2026-04-02T12:35:02.447731Z","text":{"format":"sqlite","version":"2026.03.24-v1","downloadUrl":"text/eng-asv/eng-asv-2026.03.24-v1.db","sha256":"faa4cd0815ac7ce3b01b6b97d380cd19e0d614a24138077b546ca4477ec803e7"}}'::jsonb,
    has_text = true,
    has_audio = false,
    is_available = true,
    updated_at = timezone('utc', now())
where translation_id = 'eng-asv';

update translation_catalog
set catalog = '{"version":"2026.03.24-v1","updatedAt":"2026-04-02T12:35:02.447731Z","text":{"format":"sqlite","version":"2026.03.24-v1","downloadUrl":"text/eng-rv/eng-rv-2026.03.24-v1.db","sha256":"7af01ab5001a28de1851eae28c1ce29e5d1701cd8bee9f5aaa8bd46933382532"}}'::jsonb,
    has_text = true,
    has_audio = false,
    is_available = true,
    updated_at = timezone('utc', now())
where translation_id = 'eng-rv';

update translation_catalog
set catalog = '{"version":"2026.03.24-v1","updatedAt":"2026-04-02T12:35:02.447731Z","text":{"format":"sqlite","version":"2026.03.24-v1","downloadUrl":"text/eng-webbe/eng-webbe-2026.03.24-v1.db","sha256":"dc48dfe5e753a44bd99b0db0efc37b3cd5fef642a817ed31536cc87d4c9fb46d"}}'::jsonb,
    has_text = true,
    has_audio = false,
    is_available = true,
    updated_at = timezone('utc', now())
where translation_id = 'eng-webbe';

update translation_catalog
set catalog = '{"version":"2026.03.24-v1","updatedAt":"2026-04-02T12:35:02.447731Z","text":{"format":"sqlite","version":"2026.03.24-v1","downloadUrl":"text/engbbe/engbbe-2026.03.24-v1.db","sha256":"7d5ca21f50757168ddc5e94fd3b9b46ba769c2197e09c4b5aeacd4fcd50e4c2d"}}'::jsonb,
    has_text = true,
    has_audio = false,
    is_available = true,
    updated_at = timezone('utc', now())
where translation_id = 'engBBE';

update translation_catalog
set catalog = '{"version":"2026.03.24-v1","updatedAt":"2026-04-02T12:35:02.447731Z","text":{"format":"sqlite","version":"2026.03.24-v1","downloadUrl":"text/engdby/engdby-2026.03.24-v1.db","sha256":"7dfe6cecc434b463aa62d3375041435f2c5db052df887304ca4f352e79711aec"}}'::jsonb,
    has_text = true,
    has_audio = false,
    is_available = true,
    updated_at = timezone('utc', now())
where translation_id = 'engDBY';

update translation_catalog
set catalog = '{"version":"2026.03.24-v1","updatedAt":"2026-04-02T12:35:02.447731Z","text":{"format":"sqlite","version":"2026.03.24-v1","downloadUrl":"text/engdra/engdra-2026.03.24-v1.db","sha256":"000a621f03fe311a55285fed3a997546405ef1aedba050855f2c59d479ef0c12"}}'::jsonb,
    has_text = true,
    has_audio = false,
    is_available = true,
    updated_at = timezone('utc', now())
where translation_id = 'engDRA';

update translation_catalog
set catalog = '{"version":"2026.03.24-v1","updatedAt":"2026-04-02T12:35:02.447731Z","text":{"format":"sqlite","version":"2026.03.24-v1","downloadUrl":"text/engasvbt/engasvbt-2026.03.24-v1.db","sha256":"df9440b4cf61174ca33621167a6ce25cee27cdd1a504f495cc5944a26c706074"}}'::jsonb,
    has_text = true,
    has_audio = false,
    is_available = true,
    updated_at = timezone('utc', now())
where translation_id = 'engasvbt';

update translation_catalog
set catalog = '{"version":"2026.03.24-v1","updatedAt":"2026-04-02T12:35:02.447731Z","text":{"format":"sqlite","version":"2026.03.24-v1","downloadUrl":"text/engbsb/engbsb-2026.03.24-v1.db","sha256":"d91c1ba052b68cc6482d8e0058d0ac01108fa1e50ae494d95055ae9d2cd1f790"},"audio":{"strategy":"stream-template","baseUrl":"audio/bsb","chapterPathTemplate":"{bookId}/{chapter}.m4a","fileExtension":"m4a","mimeType":"audio/mp4"}}'::jsonb,
    has_text = true,
    has_audio = true,
    is_available = true,
    updated_at = timezone('utc', now())
where translation_id = 'engbsb';

update translation_catalog
set catalog = '{"version":"2026.03.24-v1","updatedAt":"2026-04-02T12:35:02.447731Z","text":{"format":"sqlite","version":"2026.03.24-v1","downloadUrl":"text/engfbv/engfbv-2026.03.24-v1.db","sha256":"3c6921c5eec5e50f5cf3bc167bb5f238c4b1bc9d7eaca9f2e4870925798ca42c"}}'::jsonb,
    has_text = true,
    has_audio = false,
    is_available = true,
    updated_at = timezone('utc', now())
where translation_id = 'engfbv';

update translation_catalog
set catalog = '{"version":"2026.03.24-v1","updatedAt":"2026-04-02T12:35:02.447731Z","text":{"format":"sqlite","version":"2026.03.24-v1","downloadUrl":"text/engwebp/engwebp-2026.03.24-v1.db","sha256":"09ee7b9c0dd794e308180a397d9ef6e85e08c8083d7f284a6eb751bed52347ec"},"audio":{"strategy":"stream-template","baseUrl":"audio/web","chapterPathTemplate":"{bookId}/{chapter}.mp3","fileExtension":"mp3","mimeType":"audio/mpeg"},"timing":{"strategy":"stream-template","baseUrl":"timing/web","chapterPathTemplate":"{bookId}_{chapterPadded}.json","fileExtension":"json","mimeType":"application/json"}}'::jsonb,
    has_text = true,
    has_audio = true,
    is_available = true,
    updated_at = timezone('utc', now())
where translation_id = 'engwebp';

update translation_catalog
set catalog = '{"version":"2026.03.24-v1","updatedAt":"2026-04-02T12:35:02.447731Z","text":{"format":"sqlite","version":"2026.03.24-v1","downloadUrl":"text/engwebpb/engwebpb-2026.03.24-v1.db","sha256":"012ff8d726ce258b5672171cc9a346732005b0d73beb08752f142802ebae11f9"}}'::jsonb,
    has_text = true,
    has_audio = false,
    is_available = true,
    updated_at = timezone('utc', now())
where translation_id = 'engwebpb';

update translation_catalog
set catalog = '{"version":"2026.03.24-v1","updatedAt":"2026-04-02T12:35:02.447731Z","text":{"format":"sqlite","version":"2026.03.24-v1","downloadUrl":"text/engwebu/engwebu-2026.03.24-v1.db","sha256":"f792b6a77ef5754f0a8012993427aba493f17ef1e0e94323182f29c0959bc145"}}'::jsonb,
    has_text = true,
    has_audio = false,
    is_available = true,
    updated_at = timezone('utc', now())
where translation_id = 'engwebu';

update translation_catalog
set catalog = '{"version":"2026.03.24-v1","updatedAt":"2026-04-02T12:35:02.447731Z","text":{"format":"sqlite","version":"2026.03.24-v1","downloadUrl":"text/engwmb/engwmb-2026.03.24-v1.db","sha256":"0f619d5a360761982f354acd00d0e2fdca4232bf7e529797dba3923f06228434"}}'::jsonb,
    has_text = true,
    has_audio = false,
    is_available = true,
    updated_at = timezone('utc', now())
where translation_id = 'engwmb';

update translation_catalog
set catalog = '{"version":"2026.03.24-v1","updatedAt":"2026-04-02T12:35:02.447731Z","text":{"format":"sqlite","version":"2026.03.24-v1","downloadUrl":"text/engwmbb/engwmbb-2026.03.24-v1.db","sha256":"5128480af1d44754fae6e8033e7bfcd427c2776bd3576c6cef9815abd5ed9de5"}}'::jsonb,
    has_text = true,
    has_audio = false,
    is_available = true,
    updated_at = timezone('utc', now())
where translation_id = 'engwmbb';

update translation_catalog
set catalog = '{"version":"2026.03.24-v1","updatedAt":"2026-04-02T12:35:02.447731Z","text":{"format":"sqlite","version":"2026.03.24-v1","downloadUrl":"text/engwyc2017/engwyc2017-2026.03.24-v1.db","sha256":"c2dc8d6a839f991a2a6a1cdb8e239b75737a7d4adac365f1cd95fd83432b5a77"}}'::jsonb,
    has_text = true,
    has_audio = false,
    is_available = true,
    updated_at = timezone('utc', now())
where translation_id = 'engwyc2017';

update translation_catalog
set catalog = '{"version":"2026.03.24-v1","updatedAt":"2026-04-02T12:35:02.447731Z","text":{"format":"sqlite","version":"2026.03.24-v1","downloadUrl":"text/engwyc2018/engwyc2018-2026.03.24-v1.db","sha256":"754402efc3c7985e834e5688a84a0df0a76e5d2502af6cc917be189c46167c9e"}}'::jsonb,
    has_text = true,
    has_audio = false,
    is_available = true,
    updated_at = timezone('utc', now())
where translation_id = 'engwyc2018';

update translation_catalog
set catalog = '{"version":"2026.03.24-v1","updatedAt":"2026-04-02T12:35:02.447731Z","text":{"format":"sqlite","version":"2026.03.24-v1","downloadUrl":"text/engylt/engylt-2026.03.24-v1.db","sha256":"7a668ec21e624b3d14a1e6b91343b5e8e1307a77c1cd1d583c91b8cd8d5652bd"}}'::jsonb,
    has_text = true,
    has_audio = false,
    is_available = true,
    updated_at = timezone('utc', now())
where translation_id = 'engylt';

update translation_catalog
set catalog = '{"version":"2026.03.24-v1","updatedAt":"2026-04-02T12:35:02.447731Z","text":{"format":"sqlite","version":"2026.03.24-v1","downloadUrl":"text/hin2017/hin2017-2026.03.24-v1.db","sha256":"5b4f23ef96d3ff4036768a1ef01f4d3d405ee5a34262dc3dcc90851d9c9802cd"}}'::jsonb,
    has_text = true,
    has_audio = false,
    is_available = true,
    updated_at = timezone('utc', now())
where translation_id = 'hin2017';

update translation_catalog
set catalog = '{"version":"2026.03.24-v1","updatedAt":"2026-04-02T12:35:02.447731Z","text":{"format":"sqlite","version":"2026.03.24-v1","downloadUrl":"text/hincv/hincv-2026.03.24-v1.db","sha256":"5f361b403c73705473267d1c1fdeb50739367cdaa6d7ddbb520409986992bbeb"}}'::jsonb,
    has_text = true,
    has_audio = false,
    is_available = true,
    updated_at = timezone('utc', now())
where translation_id = 'hincv';

update translation_catalog
set catalog = '{"version":"2026.03.24-v1","updatedAt":"2026-04-02T12:35:02.447731Z","text":{"format":"sqlite","version":"2026.03.24-v1","downloadUrl":"text/npiulb/npiulb-2026.03.24-v1.db","sha256":"57c0d138a48e09065ab95d548a35aa6fd39a0f68bc9ba6013fa0203ec1969efc"},"audio":{"baseUrl":"audio/npiulb","mimeType":"audio/mpeg","strategy":"stream-template","fileExtension":"mp3","chapterPathTemplate":"{bookId}/{chapter}.mp3"},"timing":{"baseUrl":"timing/npiulb","mimeType":"application/json","strategy":"stream-template","fileExtension":"json","chapterPathTemplate":"{bookId}/{chapter}.json"}}'::jsonb,
    has_text = true,
    has_audio = true,
    is_available = true,
    updated_at = timezone('utc', now())
where translation_id = 'npiulb';

update translation_catalog
set catalog = '{"version":"2026.03.24-v1","updatedAt":"2026-04-02T12:35:02.447731Z","text":{"format":"sqlite","version":"2026.03.24-v1","downloadUrl":"text/sparv1909/sparv1909-2026.03.24-v1.db","sha256":"7aea34f5b35fa87724d558e3a59db28c3d11196b75ec4e1aec5dae677ddbe1a4"}}'::jsonb,
    has_text = true,
    has_audio = false,
    is_available = true,
    updated_at = timezone('utc', now())
where translation_id = 'spaRV1909';

update translation_catalog
set catalog = '{"version":"2026.03.24-v1","updatedAt":"2026-04-02T12:35:02.447731Z","text":{"format":"sqlite","version":"2026.03.24-v1","downloadUrl":"text/spabes/spabes-2026.03.24-v1.db","sha256":"83d7922c1497d620cdcc2e0c3e82c2aa9f54781ef95182b5a081cc82b5eea385"}}'::jsonb,
    has_text = true,
    has_audio = false,
    is_available = true,
    updated_at = timezone('utc', now())
where translation_id = 'spabes';

update translation_catalog
set catalog = '{"version":"2026.03.24-v1","updatedAt":"2026-04-02T12:35:02.447731Z","text":{"format":"sqlite","version":"2026.03.24-v1","downloadUrl":"text/spablm/spablm-2026.03.24-v1.db","sha256":"2a43442ffc6eb1d3374da43560a32dbbe8ff16a77e1be05043097b1b665e1ca4"}}'::jsonb,
    has_text = true,
    has_audio = false,
    is_available = true,
    updated_at = timezone('utc', now())
where translation_id = 'spablm';

update translation_catalog
set catalog = '{"version":"2026.03.24-v1","updatedAt":"2026-04-02T12:35:02.447731Z","text":{"format":"sqlite","version":"2026.03.24-v1","downloadUrl":"text/spaonbv/spaonbv-2026.03.24-v1.db","sha256":"d23d3191ab8cf07ee3c143741c46e0bfd78bc96e1e730b629d155cf00d913d1a"}}'::jsonb,
    has_text = true,
    has_audio = false,
    is_available = true,
    updated_at = timezone('utc', now())
where translation_id = 'spaonbv';

update translation_catalog
set catalog = '{"version":"2026.03.24-v1","updatedAt":"2026-04-02T12:35:02.447731Z","text":{"format":"sqlite","version":"2026.03.24-v1","downloadUrl":"text/spapddpt/spapddpt-2026.03.24-v1.db","sha256":"996e067eea7ff15813587a8bba8585395e4c448bf4c4416b35e844b14521e61d"}}'::jsonb,
    has_text = true,
    has_audio = false,
    is_available = true,
    updated_at = timezone('utc', now())
where translation_id = 'spapddpt';

update translation_catalog
set catalog = '{"version":"2026.03.24-v1","updatedAt":"2026-04-02T12:35:02.447731Z","text":{"format":"sqlite","version":"2026.03.24-v1","downloadUrl":"text/sparvg/sparvg-2026.03.24-v1.db","sha256":"4ae11bd412157c0b3c23215277d5b325e2c2a145d6d5e23e532984a7e7e965c2"}}'::jsonb,
    has_text = true,
    has_audio = false,
    is_available = true,
    updated_at = timezone('utc', now())
where translation_id = 'sparvg';

update translation_catalog
set catalog = '{"version":"2026.03.24-v1","updatedAt":"2026-04-02T12:35:02.447731Z","text":{"format":"sqlite","version":"2026.03.24-v1","downloadUrl":"text/spav1602p/spav1602p-2026.03.24-v1.db","sha256":"a64c94c6cf9cbaaa1a81648bd4a43e1725996ad99b9415c34606d3952a373eb8"}}'::jsonb,
    has_text = true,
    has_audio = false,
    is_available = true,
    updated_at = timezone('utc', now())
where translation_id = 'spav1602p';

update translation_catalog
set catalog = '{"version":"2026.03.24-v1","updatedAt":"2026-04-02T12:35:02.447731Z","text":{"format":"sqlite","version":"2026.03.24-v1","downloadUrl":"text/spavbl/spavbl-2026.03.24-v1.db","sha256":"94668c01909215c97c228ca4dfb426f88f3e41073c26fc437116239de74befe6"}}'::jsonb,
    has_text = true,
    has_audio = false,
    is_available = true,
    updated_at = timezone('utc', now())
where translation_id = 'spavbl';

commit;
