-- Remote crash reporting (report-app-errors edge function + admin "App errors" page).
--
-- Apply BEFORE deploying report-app-errors. Until the function is deployed nothing writes
-- here; app builds that predate the crash reporter never call it, and builds that do keep
-- their reports queued on the device (a 404/5xx is retried later), so either order is safe
-- for the app. The function refuses to write (503) while the budget RPC below is missing.
--
-- Privacy: rows carry no user id, no IP address and no free text beyond the scrubbed,
-- truncated error message. install_id is a random per-install UUID generated by the app and
-- never linked to an account. Rows are service-role only and purged after 90 days.

CREATE TABLE IF NOT EXISTS public.app_error_reports (
  -- Client-generated report id, so a retried upload is ignored rather than duplicated.
  id uuid PRIMARY KEY,
  occurred_at timestamptz NOT NULL,
  received_at timestamptz NOT NULL DEFAULT now(),
  kind text NOT NULL CHECK (kind IN ('fatal', 'error', 'boundary', 'rejection')),
  is_fatal boolean NOT NULL DEFAULT false,
  fingerprint text NOT NULL CHECK (char_length(fingerprint) BETWEEN 1 AND 64),
  error_name text NOT NULL CHECK (char_length(error_name) BETWEEN 1 AND 64),
  message text NOT NULL CHECK (char_length(message) <= 500),
  stack_frames text[] NOT NULL DEFAULT '{}'::text[]
    CHECK (cardinality(stack_frames) <= 8 AND char_length(array_to_string(stack_frames, '')) <= 1600),
  component_stack text CHECK (char_length(component_stack) <= 1000),
  screen text CHECK (char_length(screen) <= 64),
  app_version text NOT NULL CHECK (char_length(app_version) BETWEEN 1 AND 32),
  build_number text CHECK (char_length(build_number) <= 32),
  platform text NOT NULL CHECK (platform IN ('ios', 'android', 'web', 'other')),
  os_version text CHECK (char_length(os_version) <= 32),
  install_id uuid
);

-- Serves both the admin window queries and the nightly purge.
CREATE INDEX IF NOT EXISTS app_error_reports_occurred_at_idx
  ON public.app_error_reports (occurred_at);

ALTER TABLE public.app_error_reports ENABLE ROW LEVEL SECURITY;
-- No policies: only the service role (which bypasses RLS) reads or writes this table.
REVOKE ALL ON TABLE public.app_error_reports FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, DELETE ON TABLE public.app_error_reports TO service_role;

COMMENT ON TABLE public.app_error_reports IS
  'Scrubbed, anonymous app crash/error reports from report-app-errors. No user ids or IPs. Service role only; purged after 90 days.';

-- Per-source budget for report-app-errors, kept in the existing UNLOGGED
-- analytics_ingest_throttle table under its own salted keys (so it never shares a budget or a
-- geo claim with analytics). A second, global counter bounds total writes per window even
-- when the flood rotates source addresses; it is charged only for requests the source's own
-- budget admits, so a single blocked source cannot use it up for everyone.
CREATE OR REPLACE FUNCTION public.consume_app_error_ingest_budget(
  p_client_key text,
  p_report_count integer,
  p_byte_count integer,
  p_window_seconds integer,
  p_max_requests integer,
  p_max_reports integer,
  p_max_bytes integer,
  p_max_global_reports integer
)
RETURNS TABLE (allowed boolean, retry_after_seconds integer)
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
  v_window interval := make_interval(secs => greatest(p_window_seconds, 1));
  v_row public.analytics_ingest_throttle;
  v_global public.analytics_ingest_throttle;
  v_client_ok boolean;
BEGIN
  INSERT INTO public.analytics_ingest_throttle AS t
    (client_key, window_started_at, request_count, event_count, byte_count)
  VALUES (p_client_key, now(), 1, greatest(p_report_count, 0), greatest(p_byte_count, 0))
  ON CONFLICT (client_key) DO UPDATE SET
    window_started_at = CASE WHEN t.window_started_at <= now() - v_window
      THEN now() ELSE t.window_started_at END,
    request_count = CASE WHEN t.window_started_at <= now() - v_window
      THEN 1 ELSE t.request_count + 1 END,
    event_count = CASE WHEN t.window_started_at <= now() - v_window
      THEN excluded.event_count ELSE t.event_count + excluded.event_count END,
    byte_count = CASE WHEN t.window_started_at <= now() - v_window
      THEN excluded.byte_count ELSE t.byte_count + excluded.byte_count END
  RETURNING * INTO v_row;

  v_client_ok := v_row.request_count <= p_max_requests
    AND v_row.event_count <= p_max_reports
    AND v_row.byte_count <= p_max_bytes;

  IF NOT v_client_ok THEN
    allowed := false;
    retry_after_seconds := greatest(
      1, ceil(extract(epoch FROM (v_row.window_started_at + v_window - now())))::integer
    );
    RETURN NEXT;
    RETURN;
  END IF;

  INSERT INTO public.analytics_ingest_throttle AS t
    (client_key, window_started_at, request_count, event_count)
  VALUES ('global:app-error-reports', now(), 1, greatest(p_report_count, 0))
  ON CONFLICT (client_key) DO UPDATE SET
    window_started_at = CASE WHEN t.window_started_at <= now() - v_window
      THEN now() ELSE t.window_started_at END,
    request_count = CASE WHEN t.window_started_at <= now() - v_window
      THEN 1 ELSE t.request_count + 1 END,
    event_count = CASE WHEN t.window_started_at <= now() - v_window
      THEN excluded.event_count ELSE t.event_count + excluded.event_count END
  RETURNING * INTO v_global;

  allowed := v_global.event_count <= p_max_global_reports;
  retry_after_seconds := CASE WHEN allowed THEN 0 ELSE greatest(
    1, ceil(extract(epoch FROM (v_global.window_started_at + v_window - now())))::integer
  ) END;

  -- Opportunistic pruning (~1 in 200 calls), mirroring consume_analytics_ingest_budget.
  IF random() < 0.005 THEN
    DELETE FROM public.analytics_ingest_throttle
      WHERE window_started_at < now() - interval '1 day'
        AND client_key <> 'global:geo-lookups';
  END IF;

  RETURN NEXT;
END;
$$;

REVOKE ALL ON FUNCTION public.consume_app_error_ingest_budget(
  text, integer, integer, integer, integer, integer, integer, integer
) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.consume_app_error_ingest_budget(
  text, integer, integer, integer, integer, integer, integer, integer
) TO service_role;

-- Retention: one constant, 90 days.
CREATE OR REPLACE FUNCTION public.purge_old_app_error_reports()
RETURNS integer
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
  retention interval := interval '90 days';
  affected integer;
BEGIN
  DELETE FROM public.app_error_reports WHERE occurred_at < now() - retention;
  GET DIAGNOSTICS affected = ROW_COUNT;
  RETURN affected;
END;
$$;

REVOKE ALL ON FUNCTION public.purge_old_app_error_reports() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.purge_old_app_error_reports() TO service_role;

-- Admin "App errors" page: top fingerprints in a window with version/platform breakdowns.
-- Called only by the admin server with the service role after its own admin check.
CREATE OR REPLACE FUNCTION public.get_admin_app_error_summary(
  p_since timestamptz,
  p_limit integer DEFAULT 50
)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = ''
AS $$
  WITH windowed AS (
    SELECT * FROM public.app_error_reports WHERE occurred_at >= p_since
  ),
  per_fingerprint AS (
    SELECT
      fingerprint,
      count(*) AS report_count,
      count(*) FILTER (WHERE is_fatal) AS fatal_count,
      count(DISTINCT install_id) AS install_count,
      min(occurred_at) AS first_seen,
      max(occurred_at) AS last_seen
    FROM windowed
    GROUP BY fingerprint
    ORDER BY count(*) DESC, max(occurred_at) DESC
    LIMIT least(greatest(coalesce(p_limit, 50), 1), 200)
  ),
  latest AS (
    SELECT DISTINCT ON (fingerprint)
      fingerprint, error_name, message, screen, kind, stack_frames, component_stack
    FROM windowed
    WHERE fingerprint IN (SELECT fingerprint FROM per_fingerprint)
    ORDER BY fingerprint, occurred_at DESC
  ),
  versions AS (
    SELECT fingerprint, jsonb_object_agg(app_version, n) AS by_version
    FROM (
      SELECT fingerprint, app_version, count(*) AS n
      FROM windowed
      WHERE fingerprint IN (SELECT fingerprint FROM per_fingerprint)
      GROUP BY fingerprint, app_version
    ) v
    GROUP BY fingerprint
  ),
  platforms AS (
    SELECT fingerprint, jsonb_object_agg(platform, n) AS by_platform
    FROM (
      SELECT fingerprint, platform, count(*) AS n
      FROM windowed
      WHERE fingerprint IN (SELECT fingerprint FROM per_fingerprint)
      GROUP BY fingerprint, platform
    ) p
    GROUP BY fingerprint
  )
  SELECT jsonb_build_object(
    'totals', (
      SELECT jsonb_build_object(
        'reports', count(*),
        'fatal', count(*) FILTER (WHERE is_fatal),
        'installs', count(DISTINCT install_id),
        'fingerprints', count(DISTINCT fingerprint)
      )
      FROM windowed
    ),
    'byVersion', (
      SELECT coalesce(jsonb_object_agg(app_version, n), '{}'::jsonb)
      FROM (SELECT app_version, count(*) AS n FROM windowed GROUP BY app_version) v
    ),
    'byPlatform', (
      SELECT coalesce(jsonb_object_agg(platform, n), '{}'::jsonb)
      FROM (SELECT platform, count(*) AS n FROM windowed GROUP BY platform) p
    ),
    'fingerprints', coalesce((
      SELECT jsonb_agg(
        jsonb_build_object(
          'fingerprint', f.fingerprint,
          'errorName', l.error_name,
          'message', l.message,
          'screen', l.screen,
          'kind', l.kind,
          'stackFrames', to_jsonb(l.stack_frames),
          'componentStack', l.component_stack,
          'reportCount', f.report_count,
          'fatalCount', f.fatal_count,
          'installCount', f.install_count,
          'firstSeen', f.first_seen,
          'lastSeen', f.last_seen,
          'byVersion', coalesce(v.by_version, '{}'::jsonb),
          'byPlatform', coalesce(p.by_platform, '{}'::jsonb)
        )
        ORDER BY f.report_count DESC, f.last_seen DESC
      )
      FROM per_fingerprint f
      JOIN latest l USING (fingerprint)
      LEFT JOIN versions v USING (fingerprint)
      LEFT JOIN platforms p USING (fingerprint)
    ), '[]'::jsonb)
  );
$$;

REVOKE ALL ON FUNCTION public.get_admin_app_error_summary(timestamptz, integer)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_admin_app_error_summary(timestamptz, integer)
  TO service_role;

-- Nightly purge, scheduled like nightly-analytics-maintenance (skipped where pg_cron is
-- absent, e.g. a local stack without the extension). The IFs are nested because PL/pgSQL
-- plans a combined condition as one query, which fails when cron.job does not exist.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
    IF NOT EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'nightly-app-error-reports-purge') THEN
      PERFORM cron.schedule(
        'nightly-app-error-reports-purge',
        '45 2 * * *',
        $cron$SELECT public.purge_old_app_error_reports();$cron$
      );
    END IF;
  END IF;
END;
$$;
