import type { DailyScriptureReference } from '../../types';

export const POPULAR_VERSE_REFERENCES: DailyScriptureReference[] = [
  { bookId: 'JHN', chapter: 3, verse: 16 },
  { bookId: 'ROM', chapter: 8, verse: 28 },
  { bookId: 'PHP', chapter: 4, verse: 13 },
  { bookId: 'JER', chapter: 29, verse: 11 },
  { bookId: 'PSA', chapter: 23, verse: 1 },
  { bookId: 'PRO', chapter: 3, verse: 5, verseEnd: 6 },
  { bookId: 'ISA', chapter: 40, verse: 31 },
  { bookId: 'MAT', chapter: 11, verse: 28 },
  { bookId: 'ROM', chapter: 12, verse: 2 },
  { bookId: 'GAL', chapter: 5, verse: 22 },
  { bookId: 'NUM', chapter: 6, verse: 24, verseEnd: 26 },
  { bookId: 'DEU', chapter: 31, verse: 6 },
  { bookId: 'JOS', chapter: 1, verse: 9 },
  { bookId: '2SA', chapter: 22, verse: 31 },
  { bookId: '2CH', chapter: 7, verse: 14 },
  { bookId: 'PSA', chapter: 34, verse: 8 },
  { bookId: 'PSA', chapter: 46, verse: 1 },
  { bookId: 'PSA', chapter: 63, verse: 1 },
  { bookId: 'PSA', chapter: 91, verse: 1 },
  { bookId: 'PSA', chapter: 103, verse: 12 },
  { bookId: 'ISA', chapter: 9, verse: 6 },
  { bookId: 'ISA', chapter: 41, verse: 10 },
  { bookId: 'ISA', chapter: 53, verse: 5 },
  { bookId: 'LAM', chapter: 3, verse: 22, verseEnd: 23 },
  { bookId: 'EZK', chapter: 36, verse: 26 },
  { bookId: 'MAT', chapter: 6, verse: 33 },
  { bookId: 'MAT', chapter: 16, verse: 24 },
  { bookId: 'MAT', chapter: 22, verse: 37, verseEnd: 39 },
  { bookId: 'MRK', chapter: 8, verse: 34 },
  { bookId: 'JHN', chapter: 10, verse: 10 },
  { bookId: 'JHN', chapter: 14, verse: 6 },
  { bookId: 'JHN', chapter: 15, verse: 13 },
  { bookId: 'JHN', chapter: 16, verse: 33 },
  { bookId: 'ACT', chapter: 1, verse: 8 },
  { bookId: 'ROM', chapter: 5, verse: 8 },
  { bookId: 'ROM', chapter: 6, verse: 23 },
  { bookId: 'ROM', chapter: 8, verse: 1 },
  { bookId: 'MAT', chapter: 4, verse: 4 },
  { bookId: 'MAT', chapter: 5, verse: 16 },
  { bookId: 'MAT', chapter: 9, verse: 37, verseEnd: 38 },
  { bookId: 'MRK', chapter: 11, verse: 24 },
  { bookId: 'LUK', chapter: 12, verse: 32 },
  { bookId: 'JHN', chapter: 5, verse: 24 },
  { bookId: 'JHN', chapter: 6, verse: 37 },
  { bookId: 'JHN', chapter: 7, verse: 38 },
  { bookId: 'JHN', chapter: 8, verse: 31, verseEnd: 32 },
  { bookId: 'JHN', chapter: 10, verse: 27, verseEnd: 28 },
  { bookId: 'JHN', chapter: 15, verse: 7 },
  { bookId: 'ACT', chapter: 2, verse: 21 },
  { bookId: 'ROM', chapter: 5, verse: 1 },
  { bookId: 'ROM', chapter: 10, verse: 13 },
  { bookId: '2CO', chapter: 9, verse: 8 },
  { bookId: 'EPH', chapter: 5, verse: 8 },
  { bookId: 'COL', chapter: 1, verse: 13 },
  { bookId: 'HEB', chapter: 13, verse: 8 },
  { bookId: 'REV', chapter: 2, verse: 10 },
  { bookId: 'REV', chapter: 21, verse: 3, verseEnd: 4 },
  { bookId: 'REV', chapter: 3, verse: 11 },
];
