import type { DailyScriptureReference } from '../../types';

export const POPULAR_VERSE_REFERENCES: DailyScriptureReference[] = [
  { bookId: 'JHN', chapter: 3, verse: 16 },
  { bookId: 'ROM', chapter: 8, verse: 28 },
  { bookId: 'PHP', chapter: 4, verse: 13 },
  { bookId: 'JER', chapter: 29, verse: 11 },
  { bookId: 'PSA', chapter: 23, verse: 1 },
  { bookId: 'PRO', chapter: 3, verse: 5, verseEnd: 6 },
  { bookId: 'ISA', chapter: 40, verse: 31 },
  { bookId: 'MAT', chapter: 11, verse: 28 },
  { bookId: 'ROM', chapter: 12, verse: 2 },
  { bookId: 'GAL', chapter: 5, verse: 22 },
  { bookId: 'NUM', chapter: 6, verse: 24, verseEnd: 26 },
  { bookId: 'DEU', chapter: 31, verse: 6 },
  { bookId: 'JOS', chapter: 1, verse: 9 },
  { bookId: '2SA', chapter: 22, verse: 31 },
  { bookId: '2CH', chapter: 7, verse: 14 },
  { bookId: 'PSA', chapter: 34, verse: 8 },
  { bookId: 'PSA', chapter: 46, verse: 1 },
  { bookId: 'PSA', chapter: 63, verse: 1 },
  { bookId: 'PSA', chapter: 91, verse: 1 },
  { bookId: 'PSA', chapter: 103, verse: 12 },
  { bookId: 'ISA', chapter: 9, verse: 6 },
  { bookId: 'ISA', chapter: 41, verse: 10 },
  { bookId: 'ISA', chapter: 53, verse: 5 },
  { bookId: 'LAM', chapter: 3, verse: 22, verseEnd: 23 },
  { bookId: 'EZK', chapter: 36, verse: 26 },
  { bookId: 'MAT', chapter: 6, verse: 33 },
  { bookId: 'MAT', chapter: 16, verse: 24 },
  { bookId: 'MAT', chapter: 22, verse: 37, verseEnd: 39 },
  { bookId: 'MRK', chapter: 8, verse: 34 },
  { bookId: 'JHN', chapter: 10, verse: 10 },
  { bookId: 'JHN', chapter: 14, verse: 6 },
  { bookId: 'JHN', chapter: 15, verse: 13 },
  { bookId: 'JHN', chapter: 16, verse: 33 },
  { bookId: 'ACT', chapter: 1, verse: 8 },
  { bookId: 'ROM', chapter: 5, verse: 8 },
  { bookId: 'ROM', chapter: 6, verse: 23 },
  { bookId: 'ROM', chapter: 8, verse: 1 },
  { bookId: 'MAT', chapter: 4, verse: 4 },
  { bookId: 'MAT', chapter: 5, verse: 16 },
  { bookId: 'MAT', chapter: 9, verse: 37, verseEnd: 38 },
  { bookId: 'MRK', chapter: 11, verse: 24 },
  { bookId: 'LUK', chapter: 12, verse: 32 },
  { bookId: 'JHN', chapter: 5, verse: 24 },
  { bookId: 'JHN', chapter: 6, verse: 37 },
  { bookId: 'JHN', chapter: 7, verse: 38 },
  { bookId: 'JHN', chapter: 8, verse: 31, verseEnd: 32 },
  { bookId: 'JHN', chapter: 10, verse: 27, verseEnd: 28 },
  { bookId: 'JHN', chapter: 15, verse: 7 },
  { bookId: 'ACT', chapter: 2, verse: 21 },
  { bookId: 'ROM', chapter: 5, verse: 1 },
  { bookId: 'ROM', chapter: 10, verse: 13 },
  { bookId: '2CO', chapter: 9, verse: 8 },
  { bookId: 'EPH', chapter: 5, verse: 8 },
  { bookId: 'COL', chapter: 1, verse: 13 },
  { bookId: 'HEB', chapter: 13, verse: 8 },
  { bookId: 'REV', chapter: 2, verse: 10 },
  { bookId: 'REV', chapter: 21, verse: 3, verseEnd: 4 },
  { bookId: 'REV', chapter: 3, verse: 11 },

  // — 100 additional uplifting verses —

  // Old Testament
  { bookId: 'GEN', chapter: 28, verse: 15 },
  { bookId: 'EXO', chapter: 14, verse: 14 },
  { bookId: 'EXO', chapter: 15, verse: 2 },
  { bookId: '1CH', chapter: 16, verse: 11 },
  { bookId: 'NEH', chapter: 8, verse: 10 },
  { bookId: 'JOB', chapter: 19, verse: 25 },
  { bookId: 'PSA', chapter: 16, verse: 8 },
  { bookId: 'PSA', chapter: 27, verse: 1 },
  { bookId: 'PSA', chapter: 32, verse: 8 },
  { bookId: 'PSA', chapter: 34, verse: 18 },
  { bookId: 'PSA', chapter: 37, verse: 4 },
  { bookId: 'PSA', chapter: 37, verse: 5 },
  { bookId: 'PSA', chapter: 46, verse: 10 },
  { bookId: 'PSA', chapter: 55, verse: 22 },
  { bookId: 'PSA', chapter: 73, verse: 26 },
  { bookId: 'PSA', chapter: 84, verse: 11 },
  { bookId: 'PSA', chapter: 91, verse: 11 },
  { bookId: 'PSA', chapter: 100, verse: 4, verseEnd: 5 },
  { bookId: 'PSA', chapter: 107, verse: 1 },
  { bookId: 'PSA', chapter: 118, verse: 24 },
  { bookId: 'PSA', chapter: 119, verse: 105 },
  { bookId: 'PSA', chapter: 121, verse: 1, verseEnd: 2 },
  { bookId: 'PSA', chapter: 139, verse: 14 },
  { bookId: 'PSA', chapter: 145, verse: 18 },
  { bookId: 'PSA', chapter: 147, verse: 3 },
  { bookId: 'PRO', chapter: 16, verse: 3 },
  { bookId: 'PRO', chapter: 16, verse: 9 },
  { bookId: 'PRO', chapter: 18, verse: 10 },
  { bookId: 'ISA', chapter: 26, verse: 3 },
  { bookId: 'ISA', chapter: 40, verse: 29 },
  { bookId: 'ISA', chapter: 43, verse: 2 },
  { bookId: 'ISA', chapter: 43, verse: 18, verseEnd: 19 },
  { bookId: 'ISA', chapter: 54, verse: 10 },
  { bookId: 'ISA', chapter: 55, verse: 8, verseEnd: 9 },
  { bookId: 'ISA', chapter: 58, verse: 11 },
  { bookId: 'ISA', chapter: 61, verse: 3 },
  { bookId: 'ISA', chapter: 65, verse: 24 },
  { bookId: 'JER', chapter: 31, verse: 3 },
  { bookId: 'JER', chapter: 33, verse: 3 },
  { bookId: 'MIC', chapter: 6, verse: 8 },
  { bookId: 'HAB', chapter: 3, verse: 17, verseEnd: 18 },
  { bookId: 'ZEP', chapter: 3, verse: 17 },
  { bookId: 'ZEC', chapter: 4, verse: 6 },

  // New Testament
  { bookId: 'MAT', chapter: 5, verse: 9 },
  { bookId: 'MAT', chapter: 5, verse: 14 },
  { bookId: 'MAT', chapter: 6, verse: 26 },
  { bookId: 'MAT', chapter: 6, verse: 34 },
  { bookId: 'MAT', chapter: 7, verse: 7 },
  { bookId: 'MAT', chapter: 19, verse: 26 },
  { bookId: 'MAT', chapter: 28, verse: 20 },
  { bookId: 'LUK', chapter: 1, verse: 37 },
  { bookId: 'LUK', chapter: 6, verse: 38 },
  { bookId: 'LUK', chapter: 10, verse: 19 },
  { bookId: 'JHN', chapter: 1, verse: 12 },
  { bookId: 'JHN', chapter: 11, verse: 25 },
  { bookId: 'JHN', chapter: 13, verse: 34 },
  { bookId: 'JHN', chapter: 14, verse: 1 },
  { bookId: 'JHN', chapter: 14, verse: 27 },
  { bookId: 'JHN', chapter: 15, verse: 5 },
  { bookId: 'ROM', chapter: 1, verse: 16 },
  { bookId: 'ROM', chapter: 8, verse: 37 },
  { bookId: 'ROM', chapter: 8, verse: 38, verseEnd: 39 },
  { bookId: 'ROM', chapter: 12, verse: 12 },
  { bookId: 'ROM', chapter: 15, verse: 13 },
  { bookId: '1CO', chapter: 2, verse: 9 },
  { bookId: '1CO', chapter: 10, verse: 13 },
  { bookId: '1CO', chapter: 13, verse: 13 },
  { bookId: '2CO', chapter: 4, verse: 17 },
  { bookId: '2CO', chapter: 5, verse: 7 },
  { bookId: '2CO', chapter: 5, verse: 17 },
  { bookId: '2CO', chapter: 12, verse: 9 },
  { bookId: 'GAL', chapter: 2, verse: 20 },
  { bookId: 'GAL', chapter: 6, verse: 9 },
  { bookId: 'EPH', chapter: 2, verse: 8, verseEnd: 9 },
  { bookId: 'EPH', chapter: 2, verse: 10 },
  { bookId: 'EPH', chapter: 3, verse: 20 },
  { bookId: 'EPH', chapter: 6, verse: 10 },
  { bookId: 'PHP', chapter: 1, verse: 6 },
  { bookId: 'PHP', chapter: 4, verse: 6, verseEnd: 7 },
  { bookId: 'PHP', chapter: 4, verse: 19 },
  { bookId: 'COL', chapter: 3, verse: 2 },
  { bookId: '1TH', chapter: 5, verse: 16, verseEnd: 18 },
  { bookId: '1TH', chapter: 5, verse: 24 },
  { bookId: '2TI', chapter: 1, verse: 7 },
  { bookId: '2TI', chapter: 4, verse: 7 },
  { bookId: 'HEB', chapter: 4, verse: 16 },
  { bookId: 'HEB', chapter: 10, verse: 23 },
  { bookId: 'HEB', chapter: 11, verse: 1 },
  { bookId: 'HEB', chapter: 12, verse: 1 },
  { bookId: 'JAS', chapter: 1, verse: 5 },
  { bookId: 'JAS', chapter: 4, verse: 8 },
  { bookId: '1PE', chapter: 2, verse: 9 },
  { bookId: '1PE', chapter: 5, verse: 7 },
  { bookId: '1PE', chapter: 5, verse: 10 },
  { bookId: '1JN', chapter: 1, verse: 9 },
  { bookId: '1JN', chapter: 3, verse: 1 },
  { bookId: '1JN', chapter: 4, verse: 4 },
  { bookId: '1JN', chapter: 4, verse: 18 },
  { bookId: '1JN', chapter: 4, verse: 19 },
  { bookId: 'REV', chapter: 22, verse: 13 },
];
