/**
 * Verse timestamp service — provides exact verse start times for audio follow-along.
 *
 * Timestamps are in SECONDS (float).
 * expo-av's currentPosition is in MILLISECONDS — divide by 1000 before comparing.
 *
 * Example:
 *   const timestamps = await getChapterTimestamps('web', 'GEN', 1);
 *   // timestamps[1] = 0.0, timestamps[2] = 4.2, ...
 *   // In bibleReaderModel getEstimatedFollowAlongVerse:
 *   //   timestamps[vn] <= currentPosition / 1000
 *
 * Source files: assets/timestamps/<TRANSLATION_UPPER>/<BOOK>_<CHAPTER_PADDED>.json
 * Generated by: npm run generate-timestamps -- --translation web
 * Bundled as: src/data/verseTimestamps.<translation>.generated.json
 * Packed by: npm run codegen-timestamps
 *
 * Translations whose catalog entry advertises a stream-template timing source are
 * fetched remotely first; the bundled tables are the offline fallback.
 */

import { getTranslationById } from '../../constants/translations';
import type { BibleTranslation } from '../../types';
import { resolveBibleAssetBaseUrl } from './bibleAssetBaseUrl';

export type VerseTimestamps = Record<number, number>;
type VerseTimestampMetadata = {
  id: string;
  hasTiming: boolean;
  timing?: {
    strategy: 'stream-template';
    baseUrl: string;
    chapterPathTemplate: string;
  };
};
export type VerseTimestampMetadataResolver = (
  translationId: string
) => VerseTimestampMetadata | null;

// Bundled timings: one generated table per translation (scripts/codegen-timestamps.mjs),
// keyed "<BOOK>_<CHAPTER_PADDED>", holding the chapter's verse start times in seconds,
// comma-separated from verse 1, with an empty slot for a verse without one. Each table is
// required the first time a chapter of that translation is looked up, so importing this
// module (bibleStore does so at launch) evaluates none of them.
type BundledTimestampTable = Readonly<Record<string, string>>;
type BundledTimestampTableLoader = () => BundledTimestampTable;

const BUNDLED_TIMESTAMP_TABLES: Record<string, BundledTimestampTableLoader> = {
  BSB: () => require('../../data/verseTimestamps.bsb.generated.json') as BundledTimestampTable,
  WEB: () => require('../../data/verseTimestamps.web.generated.json') as BundledTimestampTable,
};

const loadedTimestampTables = new Map<string, BundledTimestampTable>();

function getBundledTimestampTable(translationKey: string): BundledTimestampTable | null {
  const cached = loadedTimestampTables.get(translationKey);
  if (cached) {
    return cached;
  }
  const load = BUNDLED_TIMESTAMP_TABLES[translationKey];
  if (!load) {
    return null;
  }
  const table = load();
  loadedTimestampTables.set(translationKey, table);
  return table;
}

function unpackChapterTimestamps(packed: string): VerseTimestamps | null {
  const result: VerseTimestamps = {};
  let verseCount = 0;
  packed.split(',').forEach((slot, index) => {
    if (slot === '') {
      return;
    }
    const seconds = Number(slot);
    if (Number.isFinite(seconds)) {
      result[index + 1] = seconds;
      verseCount += 1;
    }
  });
  return verseCount > 0 ? result : null;
}

const REMOTE_TIMESTAMP_FETCH_TIMEOUT_MS = 10000;
const MAX_VERSE_TIMESTAMP_CACHE_SIZE = 20;
const verseTimestampCache = new Map<string, VerseTimestamps | null>();
const TIMING_TEMPLATE_PLACEHOLDERS = new Set(['{bookId}', '{chapter}', '{chapterPadded}']);

function buildVerseTimestampMetadataFromTranslation(
  translation: Pick<BibleTranslation, 'id' | 'catalog'> | null
): VerseTimestampMetadata | null {
  const catalogTiming = translation?.catalog?.timing;
  if (!catalogTiming || catalogTiming.strategy !== 'stream-template') {
    return translation
      ? {
          id: translation.id,
          hasTiming: false,
        }
      : null;
  }

  return {
    id: translation.id,
    hasTiming: true,
    timing: {
      strategy: 'stream-template',
      baseUrl: catalogTiming.baseUrl,
      chapterPathTemplate: catalogTiming.chapterPathTemplate,
    },
  };
}

export function createVerseTimestampMetadataResolverFromTranslations(
  translations: readonly BibleTranslation[]
): VerseTimestampMetadataResolver {
  const translationsById = new Map(
    translations.map((translation) => [translation.id, translation])
  );

  return (translationId) =>
    buildVerseTimestampMetadataFromTranslation(
      translationsById.get(translationId) ?? getTranslationById(translationId) ?? null
    );
}

const defaultVerseTimestampMetadataResolver: VerseTimestampMetadataResolver = (translationId) =>
  buildVerseTimestampMetadataFromTranslation(getTranslationById(translationId) ?? null);

let verseTimestampMetadataResolver: VerseTimestampMetadataResolver =
  defaultVerseTimestampMetadataResolver;

export function setVerseTimestampMetadataResolver(
  resolver: VerseTimestampMetadataResolver | null
): void {
  verseTimestampMetadataResolver = resolver ?? defaultVerseTimestampMetadataResolver;
  clearVerseTimestampCache();
}

export function syncVerseTimestampMetadataResolverWithTranslations(
  translations: readonly BibleTranslation[]
): void {
  setVerseTimestampMetadataResolver(
    createVerseTimestampMetadataResolverFromTranslations(translations)
  );
}

function resolveVerseTimestampMetadata(translationId: string): VerseTimestampMetadata | null {
  try {
    return verseTimestampMetadataResolver(translationId);
  } catch (error) {
    console.warn('[Bible] Failed to resolve verse timestamp metadata:', error);
    return null;
  }
}

function buildRemoteTimestampUrl(
  baseUrl: string,
  chapterPathTemplate: string,
  bookId: string,
  chapter: number
): string | null {
  if (!baseUrl || !chapterPathTemplate) {
    return null;
  }

  const normalizedBaseUrl = resolveBibleAssetBaseUrl(baseUrl);
  if (!normalizedBaseUrl) {
    return null;
  }

  const chapterPadded = String(chapter).padStart(3, '0');
  const path = chapterPathTemplate
    .replaceAll('{bookId}', bookId)
    .replaceAll('{chapter}', String(chapter))
    .replaceAll('{chapterPadded}', chapterPadded);

  if (Array.from(TIMING_TEMPLATE_PLACEHOLDERS).some((placeholder) => path.includes(placeholder))) {
    return null;
  }

  return `${normalizedBaseUrl}/${path.replace(/^\/+/, '')}`;
}

function parseTimestampJson(raw: Record<string, unknown>): VerseTimestamps | null {
  const result: VerseTimestamps = {};

  for (const [key, value] of Object.entries(raw)) {
    const verseNumber = Number(key);
    if (!Number.isNaN(verseNumber) && typeof value === 'number' && Number.isFinite(value)) {
      result[verseNumber] = value;
    }
  }

  return Object.keys(result).length > 0 ? result : null;
}

async function fetchRemoteChapterTimestamps(
  translationId: string,
  bookId: string,
  chapter: number
): Promise<VerseTimestamps | null> {
  const metadata = resolveVerseTimestampMetadata(translationId);
  if (!metadata?.hasTiming || metadata.timing?.strategy !== 'stream-template') {
    return null;
  }

  const url = buildRemoteTimestampUrl(
    metadata.timing.baseUrl,
    metadata.timing.chapterPathTemplate,
    bookId,
    chapter
  );
  if (!url) {
    return null;
  }

  const cacheKey = `${translationId.toUpperCase()}/${bookId}_${String(chapter).padStart(3, '0')}`;
  if (verseTimestampCache.has(cacheKey)) {
    const cached = verseTimestampCache.get(cacheKey) ?? null;
    // Re-insert to move this key to MRU position so the LRU eviction order stays accurate.
    verseTimestampCache.delete(cacheKey);
    verseTimestampCache.set(cacheKey, cached);
    return cached;
  }

  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), REMOTE_TIMESTAMP_FETCH_TIMEOUT_MS);

  try {
    const response = await fetch(url, {
      headers: {
        Accept: 'application/json',
      },
      signal: controller.signal,
    });

    if (!response.ok) {
      if (verseTimestampCache.size >= MAX_VERSE_TIMESTAMP_CACHE_SIZE) {
        verseTimestampCache.delete(verseTimestampCache.keys().next().value as string);
      }
      verseTimestampCache.set(cacheKey, null);
      return null;
    }

    const payload = (await response.json()) as unknown;
    const parsed = isTimestampRecord(payload) ? parseTimestampJson(payload) : null;
    if (verseTimestampCache.size >= MAX_VERSE_TIMESTAMP_CACHE_SIZE) {
      verseTimestampCache.delete(verseTimestampCache.keys().next().value as string);
    }
    verseTimestampCache.set(cacheKey, parsed);
    return parsed;
  } catch {
    if (verseTimestampCache.size >= MAX_VERSE_TIMESTAMP_CACHE_SIZE) {
      verseTimestampCache.delete(verseTimestampCache.keys().next().value as string);
    }
    verseTimestampCache.set(cacheKey, null);
    return null;
  } finally {
    clearTimeout(timeoutId);
  }
}

function isTimestampRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

export function clearVerseTimestampCache(): void {
  verseTimestampCache.clear();
}

/**
 * Returns verse timestamps for a given chapter, or null if not available.
 *
 * translationId: 'web' | 'bsb' (lowercase, matches translation IDs in the app)
 * bookId: 3-letter book ID e.g. 'GEN', 'MAT', '1CO' (matches src/constants/books.ts)
 * chapter: 1-indexed chapter number
 *
 * Falls back to word-weight estimation in bibleReaderModel when null is returned.
 */
export async function getChapterTimestamps(
  translationId: string,
  bookId: string,
  chapter: number
): Promise<VerseTimestamps | null> {
  const remoteTimestamps = await fetchRemoteChapterTimestamps(translationId, bookId, chapter);
  if (remoteTimestamps) {
    return remoteTimestamps;
  }

  try {
    const table = getBundledTimestampTable(translationId.toUpperCase());
    const packed = table?.[`${bookId}_${String(chapter).padStart(3, '0')}`];
    return typeof packed === 'string' ? unpackChapterTimestamps(packed) : null;
  } catch {
    // Gracefully return null if the bundled table is missing or malformed
    return null;
  }
}

/**
 * Returns true if timestamps are available for a translation.
 * Use to conditionally show follow-along UI affordances.
 */
export function hasTimestampsForTranslation(translationId: string): boolean {
  if (resolveVerseTimestampMetadata(translationId)?.hasTiming) {
    return true;
  }

  return translationId.toUpperCase() in BUNDLED_TIMESTAMP_TABLES;
}
