/**
 * Splits the public atlas snapshot into the small files the /languages pages
 * read on the server: one index for listings, sitemaps and static params, and
 * per-slug shards so rendering one page reads ~1/64 of the language data.
 * Generated by `npm run atlas:pages:build`; nothing here ships to the browser.
 */
import { scriptureStatus } from '../../admin/lib/language-atlas/model';
import type {
  AtlasIndex,
  AtlasLocation,
  AtlasRecord,
  AtlasSource,
  ScriptureStatus,
} from '../../admin/lib/language-atlas/types';
import { normalizeLanguageName } from './language-name';
import { hasLanguagePage, languageCode, languageShard, languageSlug } from './language-slug';
import type { AtlasProject } from './public-atlas-projects';

export const LANGUAGE_PAGE_SHARD_COUNT = 64;
export const LANGUAGE_PAGES_SCHEMA_VERSION = 2;

/** Best first: a macrolanguage takes the first of these that it or a member has. */
export const SCRIPTURE_STATUS_ORDER: readonly ScriptureStatus[] = [
  'bible',
  'nt',
  'portions',
  'started',
  'needed',
  'unknown',
];

/** ISO 639-3 macrolanguage code → active member language codes. */
export type MacrolanguageMap = Readonly<Record<string, readonly string[]>>;
/** Neighbours on each side in the primary country's alphabetical list. */
const RELATED_EACH_SIDE = 4;

export interface LanguagePageCountry {
  code: string;
  name: string;
}

export interface LanguagePageDialect {
  name: string;
  status: ScriptureStatus;
}

export interface LanguagePageLink {
  slug: string;
  label: string;
  status: ScriptureStatus;
}

export type LanguagePageSource = Pick<
  AtlasSource,
  'id' | 'name' | 'url' | 'attribution' | 'license'
>;

export interface LanguagePage {
  slug: string;
  id: string;
  name: string;
  /** Name plus a qualifier when another language shares the name. */
  label: string;
  aliases: string[];
  iso6393: string | null;
  glottocode: string | null;
  rolvCode: string | null;
  family: string | null;
  countries: LanguagePageCountry[];
  /** Source-reported; never inherited from a parent or people group. */
  population: number | null;
  /**
   * The status shown. For an ISO 639-3 macrolanguage it is the best of its own
   * and its members' statuses, so "Arabic" is not red while Standard Arabic
   * has a Bible.
   */
  status: ScriptureStatus;
  /** Members whose Scripture gives a macrolanguage its status; empty when the status is its own. */
  statusVia: LanguagePageLink[];
  /** ISO 639-3 member languages when this is a macrolanguage, best status first. */
  members: LanguagePageLink[];
  /** The macrolanguages this language is a member of. */
  memberOf: LanguagePageLink[];
  /**
   * A page with no code and no country says almost nothing. It stays reachable
   * but is left out of the sitemap, and either points search engines at the
   * coded language of the same name (`canonicalSlug`) or asks them not to index it.
   */
  indexable: boolean;
  /** The page search engines should treat as the original; usually this page. */
  canonicalSlug: string;
  sourceIds: string[];
  dialects: LanguagePageDialect[];
  projects: AtlasProject[];
  related: { country: LanguagePageCountry; languages: LanguagePageLink[] } | null;
}

export interface LanguageIndexEntry {
  slug: string;
  label: string;
  status: ScriptureStatus;
  /** An Every Language recording project is linked to this language or a dialect. */
  project: boolean;
  /** Listed in the sitemap: not a thin page. */
  sitemap: boolean;
}

export interface LanguagePagesMeta {
  schemaVersion: typeof LANGUAGE_PAGES_SCHEMA_VERSION;
  generatedAt: string;
  shardCount: number;
  languageCount: number;
  /** Pages listed in the sitemap. */
  sitemapCount: number;
  statusCounts: Partial<Record<ScriptureStatus, number>>;
  sources: LanguagePageSource[];
}

export interface LanguagePagesBuild {
  meta: LanguagePagesMeta;
  entries: LanguageIndexEntry[];
  shards: Record<string, LanguagePage>[];
}

const collator = new Intl.Collator('en', { sensitivity: 'base', numeric: true });

/**
 * Languages with a full Bible or New Testament, or an active recording
 * project, are rendered at build time (~2,600 pages). The rest render on
 * first request and are then cached, so the build stays fast.
 */
export function shouldPrerenderLanguage(entry: Pick<LanguageIndexEntry, 'status' | 'project'>) {
  return entry.status === 'bible' || entry.status === 'nt' || entry.project;
}

/** Records with no ISO, Glottolog or ROLV code and no country: thin, tracker-only pages. */
export function isThinLanguage(record: {
  iso6393: string | null;
  glottocode: string | null;
  rolvCode: string | null;
  countryCodes: readonly string[];
}): boolean {
  return !record.iso6393 && !record.glottocode && !record.rolvCode && !record.countryCodes.length;
}

const statusRank = (status: ScriptureStatus) => SCRIPTURE_STATUS_ORDER.indexOf(status);

/**
 * A macrolanguage's status is the best of its own and its members'; members
 * are credited only when they beat its own. Scripture is recorded against the
 * member languages, so "Arabic" alone would otherwise read "No known Scripture".
 */
export function rollUpScriptureStatus(
  own: ScriptureStatus,
  members: readonly LanguagePageLink[]
): { status: ScriptureStatus; via: LanguagePageLink[] } {
  const best = members.reduce<ScriptureStatus>(
    (status, member) => (statusRank(member.status) < statusRank(status) ? member.status : status),
    own
  );
  return {
    status: best,
    via: best === own ? [] : members.filter((member) => member.status === best),
  };
}

/** The nearest `language` ancestor, following dialect-of-dialect chains safely. */
function languageAncestor(
  record: AtlasRecord,
  byId: ReadonlyMap<string, AtlasRecord>
): AtlasRecord | null {
  const visited = new Set<string>();
  let current: AtlasRecord | undefined = record;
  while (current && !visited.has(current.id)) {
    if (current.kind === 'language') return current;
    visited.add(current.id);
    current = current.parentId ? byId.get(current.parentId) : undefined;
  }
  return null;
}

/** Above this many countries a language is not given a single main country. */
const MAX_COUNTRIES_FOR_MAIN = 3;

/**
 * The country a language is mainly spoken in, or null when the data cannot
 * say. Country codes are stored alphabetically, so the first one is not it
 * (Yoruba starts with Burkina Faso). The reference location names the country
 * when it can; otherwise, for a language of a few countries, the country whose
 * source placement is nearest the reference point. Placements are too rough to
 * pick one country for a widespread language (English's nearest is the Isle
 * of Man), so none is claimed.
 */
function primaryCountry(language: AtlasRecord): string | null {
  const reference = language.location;
  const listed = (code: string | null | undefined): code is string =>
    Boolean(code && language.countryCodes.includes(code));
  if (listed(reference?.countryCode)) return reference.countryCode;
  if (language.countryCodes.length === 1) return language.countryCodes[0];
  if (reference && language.countryCodes.length <= MAX_COUNTRIES_FOR_MAIN) {
    const scale = Math.cos((reference.latitude * Math.PI) / 180);
    const distance = (point: AtlasLocation) =>
      (point.latitude - reference.latitude) ** 2 +
      ((point.longitude - reference.longitude) * scale) ** 2;
    const nearest = (language.locations ?? [])
      .filter((point) => listed(point.countryCode))
      .sort((a, b) => distance(a) - distance(b))[0];
    if (nearest?.countryCode) return nearest.countryCode;
  }
  return null;
}

/** "Tamang: Eastern" is shown as "Eastern" on the Tamang page, matching the source or cleaned name. */
function dialectName(dialect: AtlasRecord, language: AtlasRecord): string {
  const name = dialect.name.replace(/\s+/g, ' ').trim();
  for (const languageName of new Set([language.name, normalizeLanguageName(language.name)])) {
    const prefix = `${languageName}:`;
    const rest = name.startsWith(prefix) ? name.slice(prefix.length).trim() : '';
    if (rest) return normalizeLanguageName(rest);
  }
  return normalizeLanguageName(name);
}

function cleanAliases(aliases: readonly string[], name: string): string[] {
  const key = (value: string) => value.toLocaleLowerCase('en');
  const seen = new Set([key(name)]);
  const cleaned: string[] = [];
  for (const alias of aliases) {
    const value = normalizeLanguageName(alias);
    if (!value || seen.has(key(value))) continue;
    seen.add(key(value));
    cleaned.push(value);
  }
  return cleaned;
}

/**
 * Titles must be unique, but 300+ language names are shared. Shared names get
 * their main country when that tells them apart ("Aari (Nepal)"), otherwise a
 * code, and as a last resort the (unique) slug. A qualifier is never allowed
 * to reproduce another language's title. When only one language sharing a
 * name is more than a thin tracker entry, it keeps the plain name ("Arabic"),
 * and the thin entries are qualified instead.
 */
function labelsFor(
  languages: readonly AtlasRecord[],
  countryNames: ReadonlyMap<string, string>,
  slugs: ReadonlyMap<string, string>
): Map<string, string> {
  const key = (value: string) => value.toLocaleLowerCase('en');
  const groups = new Map<string, AtlasRecord[]>();
  for (const language of languages) {
    groups.set(key(language.name), [...(groups.get(key(language.name)) ?? []), language]);
  }
  const labels = new Map<string, string>();
  const taken = new Set<string>();
  const plain = new Map<AtlasRecord[], AtlasRecord>();
  for (const group of groups.values()) {
    const full = group.filter((language) => !isThinLanguage(language));
    const owner = group.length === 1 ? group[0] : full.length === 1 ? full[0] : undefined;
    if (!owner) continue;
    plain.set(group, owner);
    labels.set(owner.id, owner.name);
    taken.add(key(owner.name));
  }
  for (const group of groups.values()) {
    if (group.length === 1) continue;
    const country = (language: AtlasRecord) => {
      const code = primaryCountry(language);
      return code ? countryNames.get(code) : undefined;
    };
    const countries = group.map(country);
    for (const language of group) {
      if (language === plain.get(group)) continue;
      const name = country(language);
      const distinctCountry =
        name && countries.filter((candidate) => candidate === name).length === 1 ? name : null;
      const qualifiers = [
        distinctCountry,
        language.iso6393,
        language.glottocode,
        languageCode(language),
        slugs.get(language.id),
      ];
      const label = qualifiers
        .filter((qualifier): qualifier is string => Boolean(qualifier))
        .map((qualifier) => `${language.name} (${qualifier})`)
        .find((candidate) => !taken.has(key(candidate)));
      if (!label) throw new Error(`No unique title for ${language.id}`);
      labels.set(language.id, label);
      taken.add(key(label));
    }
  }
  return labels;
}

function relatedLanguages(
  languages: readonly LanguageIndexEntry[],
  position: number
): LanguageIndexEntry[] {
  if (languages.length <= RELATED_EACH_SIDE * 2 + 1)
    return languages.filter((_, index) => index !== position);
  const chosen: LanguageIndexEntry[] = [];
  for (let offset = -RELATED_EACH_SIDE; offset <= RELATED_EACH_SIDE; offset++) {
    if (offset !== 0)
      chosen.push(languages[(position + offset + languages.length) % languages.length]);
  }
  return chosen.sort((a, b) => collator.compare(a.label, b.label));
}

export function buildLanguagePages(
  index: AtlasIndex,
  projects: readonly AtlasProject[],
  shardCount = LANGUAGE_PAGE_SHARD_COUNT,
  macrolanguages: MacrolanguageMap = {}
): LanguagePagesBuild {
  const byId = new Map(index.records.map((record) => [record.id, record]));
  const countryNames = new Map(index.countries.map((country) => [country.code, country.name]));
  const pageRecords = index.records.filter(
    (record) => record.kind === 'language' && hasLanguagePage(record)
  );

  // Slugs come from the source name so a tidied display name never moves a URL;
  // the atlas client builds the same slug from the same record.
  const slugs = new Map<string, string>();
  const seen = new Set<string>();
  for (const language of pageRecords) {
    const slug = languageSlug(language);
    if (seen.has(slug)) throw new Error(`Duplicate language slug ${slug} (${language.id})`);
    seen.add(slug);
    slugs.set(language.id, slug);
  }
  const languages = pageRecords.map((language) => ({
    ...language,
    name: normalizeLanguageName(language.name),
  }));
  const labels = labelsFor(languages, countryNames, slugs);

  const dialects = new Map<string, LanguagePageDialect[]>();
  for (const record of index.records) {
    if (record.kind !== 'dialect') continue;
    const language = languageAncestor(record, byId);
    if (!language) continue;
    const list = dialects.get(language.id) ?? [];
    const dialect = {
      name: dialectName(record, language),
      status: scriptureStatus(record),
    };
    // Unreconciled source records can repeat a variety; show each name and status once.
    if (!list.some((item) => item.name === dialect.name && item.status === dialect.status))
      list.push(dialect);
    dialects.set(language.id, list);
  }

  const projectsByLanguage = new Map<string, AtlasProject[]>();
  for (const project of projects) {
    const linked = project.recordId ? byId.get(project.recordId) : undefined;
    const language = linked ? languageAncestor(linked, byId) : null;
    if (language)
      projectsByLanguage.set(language.id, [
        ...(projectsByLanguage.get(language.id) ?? []),
        project,
      ]);
  }

  const link = (language: AtlasRecord, status = scriptureStatus(language)): LanguagePageLink => ({
    slug: slugs.get(language.id)!,
    label: labels.get(language.id)!,
    status,
  });
  const byStatusThenLabel = (a: LanguagePageLink, b: LanguagePageLink) =>
    statusRank(a.status) - statusRank(b.status) || collator.compare(a.label, b.label);

  // ISO 639-3 macrolanguages: members are the page languages carrying a member code.
  const byIso = new Map<string, AtlasRecord[]>();
  for (const language of languages) {
    if (language.iso6393)
      byIso.set(language.iso6393, [...(byIso.get(language.iso6393) ?? []), language]);
  }
  const members = new Map<string, LanguagePageLink[]>();
  const macrolanguageOf = new Map<string, AtlasRecord[]>();
  for (const language of languages) {
    const codes = language.iso6393 ? macrolanguages[language.iso6393] : undefined;
    if (!codes) continue;
    const list = codes
      .flatMap((code) => byIso.get(code) ?? [])
      .filter((member) => member.id !== language.id);
    if (!list.length) continue;
    // Within a status, the most widely spoken member comes first, so the badge
    // reads "via Standard Arabic" rather than the alphabetically first member.
    const reach = (member: AtlasRecord) => [member.population ?? -1, member.countryCodes.length];
    const ranked = [...list].sort((a, b) => {
      const [populationA, countriesA] = reach(a);
      const [populationB, countriesB] = reach(b);
      return (
        statusRank(scriptureStatus(a)) - statusRank(scriptureStatus(b)) ||
        populationB - populationA ||
        countriesB - countriesA ||
        collator.compare(labels.get(a.id)!, labels.get(b.id)!)
      );
    });
    members.set(
      language.id,
      ranked.map((member) => link(member))
    );
    for (const member of list)
      macrolanguageOf.set(member.id, [...(macrolanguageOf.get(member.id) ?? []), language]);
  }
  const rollUps = new Map(
    languages.map((language) => [
      language.id,
      rollUpScriptureStatus(scriptureStatus(language), members.get(language.id) ?? []),
    ])
  );
  const statusOf = (language: AtlasRecord) => rollUps.get(language.id)!.status;

  // A thin page named exactly like one coded language defers to that language's page.
  const nameKey = (name: string) => name.toLocaleLowerCase('en');
  const codedByName = new Map<string, AtlasRecord[]>();
  for (const language of languages) {
    if (!(language.iso6393 || language.glottocode || language.rolvCode)) continue;
    const key = nameKey(language.name);
    codedByName.set(key, [...(codedByName.get(key) ?? []), language]);
  }
  const canonicalOf = (language: AtlasRecord): string | null => {
    if (!isThinLanguage(language)) return null;
    const matches = codedByName.get(nameKey(language.name)) ?? [];
    return matches.length === 1 ? slugs.get(matches[0].id)! : null;
  };

  const entries: LanguageIndexEntry[] = languages
    .map((language) => ({
      slug: slugs.get(language.id)!,
      label: labels.get(language.id)!,
      status: statusOf(language),
      project: projectsByLanguage.has(language.id),
      sitemap: !isThinLanguage(language),
    }))
    .sort((a, b) => collator.compare(a.label, b.label) || a.slug.localeCompare(b.slug));
  const entryBySlug = new Map(entries.map((entry) => [entry.slug, entry]));

  const byCountry = new Map<string, LanguageIndexEntry[]>();
  for (const language of languages) {
    const code = primaryCountry(language);
    if (code && countryNames.has(code))
      byCountry.set(code, [
        ...(byCountry.get(code) ?? []),
        entryBySlug.get(slugs.get(language.id)!)!,
      ]);
  }
  for (const list of byCountry.values()) list.sort((a, b) => collator.compare(a.label, b.label));

  const shards: Record<string, LanguagePage>[] = Array.from({ length: shardCount }, () => ({}));
  const statusCounts: Partial<Record<ScriptureStatus, number>> = {};
  for (const language of languages) {
    const slug = slugs.get(language.id)!;
    const status = statusOf(language);
    const canonical = canonicalOf(language);
    statusCounts[status] = (statusCounts[status] ?? 0) + 1;
    const primary = primaryCountry(language);
    const neighbours = primary ? byCountry.get(primary) : undefined;
    const page: LanguagePage = {
      slug,
      id: language.id,
      name: language.name,
      label: labels.get(language.id)!,
      aliases: cleanAliases(language.aliases, language.name),
      iso6393: language.iso6393,
      glottocode: language.glottocode,
      rolvCode: language.rolvCode,
      family: language.family,
      // The main country (when known) first, then the rest by name.
      countries: language.countryCodes
        .map((code) => ({ code, name: countryNames.get(code) ?? code }))
        .sort(
          (a, b) =>
            Number(b.code === primary) - Number(a.code === primary) ||
            collator.compare(a.name, b.name)
        ),
      population:
        language.population !== null && Number.isFinite(language.population)
          ? language.population
          : null,
      status,
      statusVia: rollUps.get(language.id)!.via,
      members: members.get(language.id) ?? [],
      memberOf: (macrolanguageOf.get(language.id) ?? [])
        .map((macrolanguage) => link(macrolanguage, statusOf(macrolanguage)))
        .sort(byStatusThenLabel),
      indexable: !isThinLanguage(language) || canonical !== null,
      canonicalSlug: canonical ?? slug,
      sourceIds: language.sourceIds,
      dialects: (dialects.get(language.id) ?? []).sort((a, b) => collator.compare(a.name, b.name)),
      projects: projectsByLanguage.get(language.id) ?? [],
      related:
        primary && neighbours && neighbours.length > 1
          ? {
              country: { code: primary, name: countryNames.get(primary)! },
              languages: relatedLanguages(
                neighbours,
                neighbours.findIndex((entry) => entry.slug === slug)
              ).map(({ slug: relatedSlug, label, status: relatedStatus }) => ({
                slug: relatedSlug,
                label,
                status: relatedStatus,
              })),
            }
          : null,
    };
    shards[languageShard(slug, shardCount)][slug] = page;
  }

  return {
    meta: {
      schemaVersion: LANGUAGE_PAGES_SCHEMA_VERSION,
      generatedAt: index.generatedAt,
      shardCount,
      languageCount: languages.length,
      sitemapCount: entries.filter((entry) => entry.sitemap).length,
      statusCounts,
      sources: index.sources.map(({ id, name, url, attribution, license }) => ({
        id,
        name,
        url,
        attribution,
        license,
      })),
    },
    entries,
    shards,
  };
}

export const LANGUAGE_PAGES_META_FILE = 'meta.json';
export const LANGUAGE_PAGES_INDEX_FILE = 'index.json.gz';

export function languageShardFile(shard: number): string {
  return `shard-${String(shard).padStart(2, '0')}.json.gz`;
}

/** File name → JSON value; `.gz` names are gzip-compressed on disk. */
export function languagePageFiles(build: LanguagePagesBuild): Record<string, unknown> {
  return {
    [LANGUAGE_PAGES_META_FILE]: build.meta,
    [LANGUAGE_PAGES_INDEX_FILE]: { languages: build.entries },
    ...Object.fromEntries(build.shards.map((shard, index) => [languageShardFile(index), shard])),
  };
}
