/**
 * Splits the public atlas snapshot into the small files the /languages pages
 * read on the server: one index for listings, sitemaps and static params, and
 * per-slug shards so rendering one page reads ~1/64 of the language data.
 * Generated by `npm run atlas:pages:build`; nothing here ships to the browser.
 */
import { scriptureStatus } from '../../admin/lib/language-atlas/model';
import type {
  AtlasIndex,
  AtlasLocation,
  AtlasRecord,
  AtlasSource,
  ScriptureStatus,
} from '../../admin/lib/language-atlas/types';
import { languageCode, languageShard, languageSlug } from './language-slug';
import type { AtlasProject } from './public-atlas-projects';

export const LANGUAGE_PAGE_SHARD_COUNT = 64;
export const LANGUAGE_PAGES_SCHEMA_VERSION = 1;
/** Neighbours on each side in the primary country's alphabetical list. */
const RELATED_EACH_SIDE = 4;

export interface LanguagePageCountry {
  code: string;
  name: string;
}

export interface LanguagePageDialect {
  name: string;
  status: ScriptureStatus;
}

export interface LanguagePageLink {
  slug: string;
  label: string;
  status: ScriptureStatus;
}

export type LanguagePageSource = Pick<
  AtlasSource,
  'id' | 'name' | 'url' | 'attribution' | 'license'
>;

export interface LanguagePage {
  slug: string;
  id: string;
  name: string;
  /** Name plus a qualifier when another language shares the name. */
  label: string;
  aliases: string[];
  iso6393: string | null;
  glottocode: string | null;
  rolvCode: string | null;
  family: string | null;
  countries: LanguagePageCountry[];
  /** Source-reported; never inherited from a parent or people group. */
  population: number | null;
  status: ScriptureStatus;
  sourceIds: string[];
  dialects: LanguagePageDialect[];
  projects: AtlasProject[];
  related: { country: LanguagePageCountry; languages: LanguagePageLink[] } | null;
}

export interface LanguageIndexEntry {
  slug: string;
  label: string;
  status: ScriptureStatus;
  /** An Every Language recording project is linked to this language or a dialect. */
  project: boolean;
}

export interface LanguagePagesMeta {
  schemaVersion: typeof LANGUAGE_PAGES_SCHEMA_VERSION;
  generatedAt: string;
  shardCount: number;
  languageCount: number;
  statusCounts: Partial<Record<ScriptureStatus, number>>;
  sources: LanguagePageSource[];
}

export interface LanguagePagesBuild {
  meta: LanguagePagesMeta;
  entries: LanguageIndexEntry[];
  shards: Record<string, LanguagePage>[];
}

const collator = new Intl.Collator('en', { sensitivity: 'base', numeric: true });

/**
 * Languages with a full Bible or New Testament, or an active recording
 * project, are rendered at build time (~2,600 pages). The rest render on
 * first request and are then cached, so the build stays fast.
 */
export function shouldPrerenderLanguage(entry: Pick<LanguageIndexEntry, 'status' | 'project'>) {
  return entry.status === 'bible' || entry.status === 'nt' || entry.project;
}

/** The nearest `language` ancestor, following dialect-of-dialect chains safely. */
function languageAncestor(
  record: AtlasRecord,
  byId: ReadonlyMap<string, AtlasRecord>
): AtlasRecord | null {
  const visited = new Set<string>();
  let current: AtlasRecord | undefined = record;
  while (current && !visited.has(current.id)) {
    if (current.kind === 'language') return current;
    visited.add(current.id);
    current = current.parentId ? byId.get(current.parentId) : undefined;
  }
  return null;
}

/** Above this many countries a language is not given a single main country. */
const MAX_COUNTRIES_FOR_MAIN = 3;

/**
 * The country a language is mainly spoken in, or null when the data cannot
 * say. Country codes are stored alphabetically, so the first one is not it
 * (Yoruba starts with Burkina Faso). The reference location names the country
 * when it can; otherwise, for a language of a few countries, the country whose
 * source placement is nearest the reference point. Placements are too rough to
 * pick one country for a widespread language (English's nearest is the Isle
 * of Man), so none is claimed.
 */
function primaryCountry(language: AtlasRecord): string | null {
  const reference = language.location;
  const listed = (code: string | null | undefined): code is string =>
    Boolean(code && language.countryCodes.includes(code));
  if (listed(reference?.countryCode)) return reference.countryCode;
  if (language.countryCodes.length === 1) return language.countryCodes[0];
  if (reference && language.countryCodes.length <= MAX_COUNTRIES_FOR_MAIN) {
    const scale = Math.cos((reference.latitude * Math.PI) / 180);
    const distance = (point: AtlasLocation) =>
      (point.latitude - reference.latitude) ** 2 +
      ((point.longitude - reference.longitude) * scale) ** 2;
    const nearest = (language.locations ?? [])
      .filter((point) => listed(point.countryCode))
      .sort((a, b) => distance(a) - distance(b))[0];
    if (nearest?.countryCode) return nearest.countryCode;
  }
  return null;
}

function dialectName(dialect: AtlasRecord, language: AtlasRecord): string {
  const prefix = `${language.name}:`;
  return dialect.name.startsWith(prefix)
    ? dialect.name.slice(prefix.length).trim() || dialect.name
    : dialect.name;
}

/**
 * Titles must be unique, but 300+ language names are shared. Shared names get
 * their main country when that tells them apart ("Aari (Nepal)"), otherwise a
 * code, and as a last resort the (unique) slug. A qualifier is never allowed
 * to reproduce another language's title.
 */
function labelsFor(
  languages: readonly AtlasRecord[],
  countryNames: ReadonlyMap<string, string>
): Map<string, string> {
  const key = (value: string) => value.toLocaleLowerCase('en');
  const groups = new Map<string, AtlasRecord[]>();
  for (const language of languages) {
    groups.set(key(language.name), [...(groups.get(key(language.name)) ?? []), language]);
  }
  const labels = new Map<string, string>();
  const taken = new Set<string>();
  for (const group of groups.values()) {
    if (group.length > 1) continue;
    labels.set(group[0].id, group[0].name);
    taken.add(key(group[0].name));
  }
  for (const group of groups.values()) {
    if (group.length === 1) continue;
    const country = (language: AtlasRecord) => {
      const code = primaryCountry(language);
      return code ? countryNames.get(code) : undefined;
    };
    const countries = group.map(country);
    for (const language of group) {
      const name = country(language);
      const distinctCountry =
        name && countries.filter((candidate) => candidate === name).length === 1 ? name : null;
      const qualifiers = [
        distinctCountry,
        language.iso6393,
        language.glottocode,
        languageCode(language),
        languageSlug(language),
      ];
      const label = qualifiers
        .filter((qualifier): qualifier is string => Boolean(qualifier))
        .map((qualifier) => `${language.name} (${qualifier})`)
        .find((candidate) => !taken.has(key(candidate)));
      if (!label) throw new Error(`No unique title for ${language.id}`);
      labels.set(language.id, label);
      taken.add(key(label));
    }
  }
  return labels;
}

function relatedLanguages(
  languages: readonly LanguageIndexEntry[],
  position: number
): LanguageIndexEntry[] {
  if (languages.length <= RELATED_EACH_SIDE * 2 + 1)
    return languages.filter((_, index) => index !== position);
  const chosen: LanguageIndexEntry[] = [];
  for (let offset = -RELATED_EACH_SIDE; offset <= RELATED_EACH_SIDE; offset++) {
    if (offset !== 0)
      chosen.push(languages[(position + offset + languages.length) % languages.length]);
  }
  return chosen.sort((a, b) => collator.compare(a.label, b.label));
}

export function buildLanguagePages(
  index: AtlasIndex,
  projects: readonly AtlasProject[],
  shardCount = LANGUAGE_PAGE_SHARD_COUNT
): LanguagePagesBuild {
  const byId = new Map(index.records.map((record) => [record.id, record]));
  const countryNames = new Map(index.countries.map((country) => [country.code, country.name]));
  const languages = index.records.filter((record) => record.kind === 'language');

  const slugs = new Map<string, string>();
  const seen = new Set<string>();
  for (const language of languages) {
    const slug = languageSlug(language);
    if (seen.has(slug)) throw new Error(`Duplicate language slug ${slug} (${language.id})`);
    seen.add(slug);
    slugs.set(language.id, slug);
  }
  const labels = labelsFor(languages, countryNames);

  const dialects = new Map<string, LanguagePageDialect[]>();
  for (const record of index.records) {
    if (record.kind !== 'dialect') continue;
    const language = languageAncestor(record, byId);
    if (!language) continue;
    const list = dialects.get(language.id) ?? [];
    const dialect = { name: dialectName(record, language), status: scriptureStatus(record) };
    // Unreconciled source records can repeat a variety; show each name and status once.
    if (!list.some((item) => item.name === dialect.name && item.status === dialect.status))
      list.push(dialect);
    dialects.set(language.id, list);
  }

  const projectsByLanguage = new Map<string, AtlasProject[]>();
  for (const project of projects) {
    const linked = project.recordId ? byId.get(project.recordId) : undefined;
    const language = linked ? languageAncestor(linked, byId) : null;
    if (language)
      projectsByLanguage.set(language.id, [
        ...(projectsByLanguage.get(language.id) ?? []),
        project,
      ]);
  }

  const entries: LanguageIndexEntry[] = languages
    .map((language) => ({
      slug: slugs.get(language.id)!,
      label: labels.get(language.id)!,
      status: scriptureStatus(language),
      project: projectsByLanguage.has(language.id),
    }))
    .sort((a, b) => collator.compare(a.label, b.label) || a.slug.localeCompare(b.slug));
  const entryBySlug = new Map(entries.map((entry) => [entry.slug, entry]));

  const byCountry = new Map<string, LanguageIndexEntry[]>();
  for (const language of languages) {
    const code = primaryCountry(language);
    if (code && countryNames.has(code))
      byCountry.set(code, [
        ...(byCountry.get(code) ?? []),
        entryBySlug.get(slugs.get(language.id)!)!,
      ]);
  }
  for (const list of byCountry.values()) list.sort((a, b) => collator.compare(a.label, b.label));

  const shards: Record<string, LanguagePage>[] = Array.from({ length: shardCount }, () => ({}));
  const statusCounts: Partial<Record<ScriptureStatus, number>> = {};
  for (const language of languages) {
    const slug = slugs.get(language.id)!;
    const status = scriptureStatus(language);
    statusCounts[status] = (statusCounts[status] ?? 0) + 1;
    const primary = primaryCountry(language);
    const neighbours = primary ? byCountry.get(primary) : undefined;
    const page: LanguagePage = {
      slug,
      id: language.id,
      name: language.name,
      label: labels.get(language.id)!,
      aliases: language.aliases,
      iso6393: language.iso6393,
      glottocode: language.glottocode,
      rolvCode: language.rolvCode,
      family: language.family,
      // The main country (when known) first, then the rest by name.
      countries: language.countryCodes
        .map((code) => ({ code, name: countryNames.get(code) ?? code }))
        .sort(
          (a, b) =>
            Number(b.code === primary) - Number(a.code === primary) ||
            collator.compare(a.name, b.name)
        ),
      population:
        language.population !== null && Number.isFinite(language.population)
          ? language.population
          : null,
      status,
      sourceIds: language.sourceIds,
      dialects: (dialects.get(language.id) ?? []).sort((a, b) => collator.compare(a.name, b.name)),
      projects: projectsByLanguage.get(language.id) ?? [],
      related:
        primary && neighbours && neighbours.length > 1
          ? {
              country: { code: primary, name: countryNames.get(primary)! },
              languages: relatedLanguages(
                neighbours,
                neighbours.findIndex((entry) => entry.slug === slug)
              ).map(({ slug: relatedSlug, label, status: relatedStatus }) => ({
                slug: relatedSlug,
                label,
                status: relatedStatus,
              })),
            }
          : null,
    };
    shards[languageShard(slug, shardCount)][slug] = page;
  }

  return {
    meta: {
      schemaVersion: LANGUAGE_PAGES_SCHEMA_VERSION,
      generatedAt: index.generatedAt,
      shardCount,
      languageCount: languages.length,
      statusCounts,
      sources: index.sources.map(({ id, name, url, attribution, license }) => ({
        id,
        name,
        url,
        attribution,
        license,
      })),
    },
    entries,
    shards,
  };
}

export const LANGUAGE_PAGES_META_FILE = 'meta.json';
export const LANGUAGE_PAGES_INDEX_FILE = 'index.json.gz';

export function languageShardFile(shard: number): string {
  return `shard-${String(shard).padStart(2, '0')}.json.gz`;
}

/** File name → JSON value; `.gz` names are gzip-compressed on disk. */
export function languagePageFiles(build: LanguagePagesBuild): Record<string, unknown> {
  return {
    [LANGUAGE_PAGES_META_FILE]: build.meta,
    [LANGUAGE_PAGES_INDEX_FILE]: { languages: build.entries },
    ...Object.fromEntries(build.shards.map((shard, index) => [languageShardFile(index), shard])),
  };
}
