export const EVERYBIBLE_SITE_URL = 'https://everybible.app';
export const EVERYBIBLE_SUPPORT_PATH = '/support';
export const EVERYBIBLE_PRIVACY_PATH = '/privacy';
export const EVERYBIBLE_TERMS_PATH = '/terms';

export const EVERYBIBLE_PRIVACY_URL = `${EVERYBIBLE_SITE_URL}${EVERYBIBLE_PRIVACY_PATH}`;
export const EVERYBIBLE_TERMS_URL = `${EVERYBIBLE_SITE_URL}${EVERYBIBLE_TERMS_PATH}`;
export const EVERYBIBLE_SUPPORT_URL = `${EVERYBIBLE_SITE_URL}${EVERYBIBLE_SUPPORT_PATH}`;

export const EVERYBIBLE_SUPPORT_EMAIL_ADDRESS = 'hello@everybible.app';
export const EVERYBIBLE_SUPPORT_EMAIL = `mailto:${EVERYBIBLE_SUPPORT_EMAIL_ADDRESS}`;
